### ISSUE TITLE
log out workflow is confusing.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#10]
when I'm away, postage logs me out. it does not say anything when that happens. then when i try to do something it goes to the login page. it's annoying.

I think this could be fixed by making it so that, on log out, it just goes to the login page.

yes, i think i like that. if anyone else has a better idea, now is the time.

**Comment by michaeltocci** [comment]
Done, the changes will be included in the next release.

I've made it so that if the websockets on the page fail to reconnect 6 times: the page automatically goes to the logout link.
