### ISSUE TITLE
Websocket update PK column

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/postage#100]
In the datasheet view,

When updated a record it goes through three color changes:
```
 red:    update has been sent, haven't received the updated record
 orange: update was successful, transaction hasn't been committed
 green:  transaction was successfully committed
```

If you update a primary key column: the record turns red (which is correct) but never turns orange then green (incorrect).

An investigation into the websocket frames reveals that when you update a `non-PK` column, the websocket gets the updated version of the record in it's response frames. However, try to update a `PK` and the only thing missing among the response frames is the updated version of the record.

My guess is the `C` generates a where clause using the `PK` column but it you update the `PK` column, the `C` where clause doesn't find the updated `PK` after it's completed the update.

**Comment by justintocci** [comment]
This is over a month old. Let's get this fixed.
