### ISSUE TITLE
Autocomplete pops up before I start typing

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#101]
Type 

"SELECT column_name1, "

At this point I get an autocomplete window, but I don't want one until I've started to type something. For example, if I went to type "column_name2", then I would want autocomplete to pop up after I type the first letter ("c"). But it pops up before that. 

![screen shot 2017-01-23 at 12 22 48 pm](https://cloud.githubusercontent.com/assets/14250339/22216956/bc8c4848-e166-11e6-8024-54ef9e4fd290.JPG)

**Comment by justintocci** [comment]
Found a related problem with Autocomplete...

See the screen shot. The only choice in the list was "pn". I typed in the full word. In this case the autocomplete should have dismissed itself.



![screen shot 2017-01-28 at 2 35 23 pm](https://cloud.githubusercontent.com/assets/14250339/22399653/1c4e218a-e567-11e6-8261-722313f41a53.JPG)

**Comment by crosstocci** [comment]
Fixed in next release.
