### ISSUE TITLE
Function List Ordering

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#114]
In the image, it seems to be ignoring the underscores while ordering. Is this intentional?

![screen shot 2017-02-21 at 11 04 28 am](https://cloud.githubusercontent.com/assets/14278246/23217600/812e27a4-f8df-11e6-8f63-8df41601baaa.png)

**Comment by justintocci** [comment]
I like it, but I'm wondering what other characters are being dropped from the sort.

**Comment by crosstocci** [comment]
It's unclear what needs to be done if anything does need to be done.
