### ISSUE TITLE
Download Schema Object Type Order

### ISSUE THREAD

**Issue by crosstocci** [workflowproducts/postage#115]
The script generated by the download schema button orders the objects incorrectly. It is sorted by object type when it should be ordering by OID.

Sorting by the OID will make it so that objects are listed in the order in which they should be created (`oid ASC`) or the the order they should be dropped (`oid DESC`).

**Comment by josephtocci** [comment]
Michael has fixed this, and I fixed an issue where it was saying DROP TRIGGERFUNCTION instead of DROP FUNCTION.

Will be seen in next release.
