### ISSUE TITLE
Delete does not update row count

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#121]
I deleted two of three records, but the total row count did not update. It said showing one of three. After a refresh of the widget, the row count was correct.

In order to fix this, we need the insert and the delete calls to return a row count, or we need to update the row count based on how many we deleted or inserted.

![screen shot 2017-02-28 at 6 41 41 pm](https://cloud.githubusercontent.com/assets/14278246/23469561/9124ad56-fe69-11e6-8360-d250db6c7c3b.png)

**Comment by crosstocci** [comment]
Fixed in next release.
