### ISSUE TITLE
table stats from PGAdmin III

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#122]
we should look at adding the table stats from PGAdmin, 

row count and such

**Comment by justintocci** [comment]
First off, above I mention "and such". I looked around and didn't see anything interesting. It's really just about the row estimate. Row counts would be way too slow.

I've pasted the code for two row estimates here so you don't have to go find the SQL to get this added to the table script. What I would like to see at the top of the table script is this:

-- Table: wtkv2.rtime; 
-- Estimated Rows: 33812
-- Last Vacuum:                 N/A, Last AutoVacuum: 02/16/2017 03:02 PM
-- Last Analyze:                 N/A, Last AutoAnalyze: 02/28/2017 02:02 PM
-- DROP TABLE wtkv2.rtime;


Estimated row count examples:
```
SELECT reltuples::BIGINT as row_estimate
FROM pg_class 
WHERE oid = 'wtkv2.rtime'::regclass;
```

'row_estimate'
33812

```
SELECT reltuples::BIGINT as row_estimate
FROM pg_class 
WHERE oid = 'test.asdf'::regclass;
```

'row_estimate'
0

Last Vacuum example:
```
SELECT relid, schemaname || '.' || relname as table_name, 
    CASE WHEN last_vacuum is not null THEN '-- ' || date_trunc('minute'::text, last_vacuum)::text END, 
    CASE WHEN last_autovacuum is not null THEN '-- ' || date_trunc('minute'::text, last_autovacuum)::text END, 
    CASE WHEN last_analyze is not null THEN '-- ' || date_trunc('minute'::text, last_analyze)::text END, 
    CASE WHEN last_autoanalyze is not null THEN '-- ' || date_trunc('minute'::text, last_autoanalyze)::text END
FROM pg_stat_user_tables
```

SELECT relid, schemaname || '.' || relname as table_name, 
    '-- Last Vacuum: ' || CASE WHEN last_vacuum is not null THEN to_char(last_vacuum, 'mm/dd/yyyy HH:MM AM') ELSE '                N/A, Last AutoVacuum: ' END 
    || CASE WHEN last_autovacuum is not null THEN to_char(last_autovacuum, 'mm/dd/yyyy HH:MM AM') ELSE '                N/A' END as "last vacuum/autovacuum", 
    '-- Last Analyze: ' || CASE WHEN last_analyze is not null THEN to_char(last_analyze, 'mm/dd/yyyy HH:MM AM') ELSE '                N/A, Last AutoAnalyze: ' END
    || CASE WHEN last_autoanalyze is not null THEN to_char(last_autoanalyze, 'mm/dd/yyyy HH:MM AM') ELSE '                N/A' END as "last analyze/autoanalyze"
FROM pg_stat_user_tables
WHERE relid = 'wtkv2.rtime'::regclass;

**Comment by nunziotocci** [comment]
I thought I should mention, we already have table statistics in the GUI.

Click on a table.

Then in the sidebar:
![capture](https://cloud.githubusercontent.com/assets/7560749/23616038/06714ff0-024e-11e7-8985-63188fc8e72c.PNG)
Click the bar chart icon (5th down):
![capture2](https://cloud.githubusercontent.com/assets/7560749/23616135/56a97434-024e-11e7-80bb-1ebc04e090fb.PNG)

**Comment by crosstocci** [comment]
Added table stats to table scripts in next release.
