### ISSUE TITLE
Install for all users on Windows

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#123]
Hi,

Firstly, thanks for writing postage - we're trialling it at work as a replacement for pgAdmin.
We are using the Windows v3.1.3 release.

I've got a few bug reports and feature requests, which I'll split up into separate issues, starting with this one.

---

Currently the Windows installer installs postage for just one user (into %LOCALAPPDATA%, I think) - could you add an option to install for all users as well (in %PROGRAMFILES%)?

Our IT group tried copying the installed files to %PROGRAMFILES%/Postage and we now run it from there, but can't be sure if any of the other issues we've encountered are due to concurrent usage of the same install.

Thanks,
Steven.

**Comment by nunziotocci** [comment]
@stevenwinfield there is now a beta release out for 3.2.0.
In this release, I added an option to install for all users to the windows installer.

Thank you!
