### ISSUE TITLE
Disable implicit BEGIN / Allow multistatement transactions

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#124]
Windows Server 2008 R2
Postage 3.1.3
Postgres 9.6.2

It seems that every SQL statement in a tab is wrapped in an implicit BEGIN/COMMIT (I assume) when executed, since just executing "BEGIN;" returns:
 
Query
WARNING:  there is already a transaction in progress
0 Rows Affected

Also all statements in a tab seem to be executed individually, so trying to do something like this:

BEGIN;
LOCK TABLE foo FOR ACCESS EXCLUSIVE;
<some DML where exclusive access is assumed>
COMMIT;

...will not have the third statement executed while holding the lock.

Is there a way to specify that the whole script should be executed in one shot?

Thanks,
Steven

**Comment by justintocci** [comment]
Hi Steven! First, thank you for everything you're doing. We really appreciate it!

You are correct, when you click 'run', a BEGIN is issued, and then your statements are split up by a parser and run one at a time. What this does is it allows us to then get the results and notices for each statement in turn. It makes it possible for us to have the nice individual windows for each result when you run multiple statements. Then at the end, a COMMIT is run. 

To do what you ask, you can simply comment out the BEGIN at the top and the COMMIT at the bottom. ROLLBACK and any other commands will work correctly. 

If you would like us to add a mode where we don't wrap all the statements in a BEGIN / COMMIT, we'd be open to adding that. What would be best for your use case?

**Comment by stevenwinfield** [comment]
Ah, I see - so it's a single BEGIN, followed by each statement in turn (which I love btw - seeing the output from multiple SELECTs was a hotly requested feature of pgAdmin), and then a single COMMIT.

I think a mode where I can chose if the implicit BEGIN/COMMIT are done would be very much welcomed.
Some commands, for example CREATE INDEX CONCURRENTLY, cannot be done inside a transaction block and so I can't use postage to execute them:

Error:

LOG:  statement: CREATE INDEX CONCURRENTLY temp_idx ON trader (name_first);
ERROR:  CREATE INDEX CONCURRENTLY cannot run inside a transaction block

**Comment by justintocci** [comment]
As a workaround until we get a mode in there, just do what we do.

COMMIT;
<your statements>
BEGIN;

**Comment by stevenwinfield** [comment]
Will do, thanks.

**Comment by justintocci** [comment]
Cross. Open a SQL tab. On the left, below the Ace icon, add a checkbox. Make the tooltip say "Autocommit". The default will be unchecked. When someone checks the box, have the RUN button add the COMMIT; command as the first statement and the BEGIN; command as the last statement.

Then, omit the first and last transaction results from the result window.

**Comment by nunziotocci** [comment]
Will be seen in next release.

**Comment by stevenwinfield** [comment]
That's great, thank you :-)
