### ISSUE TITLE
Zoom level is not saved and often reset

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#126]
Windows Server 2008 R2
Postage 3.1.3
Postgres 9.6.2

I have been using postage on a monitor with a high DPI, and so have been increasing the zoom level to make things more readable (with Ctrl-Shift-=).

However, I've found that the zoom level is not saved from one session to the next, and within one session the zoom level is reset by certain operations, for example by clicking on the Home button:
![image](https://cloud.githubusercontent.com/assets/1327493/23518063/2b18af6a-ff6a-11e6-862b-2f2b91ac8a66.png)
->
![image](https://cloud.githubusercontent.com/assets/1327493/23518077/3739888c-ff6a-11e6-8d76-dce8e250f151.png)

Thanks,
Steve.

**Comment by stevenwinfield** [comment]
On the same topic, perhaps Ctrl+Mousewheel could alter the zoom level as well - Chrome has this keybinding (if you can call it that).

**Comment by michaeltocci** [comment]
Awesome idea!

We'll have Postage save the zoom level as a cookie so that it'll be a local preference that'll be remembered across sessions.

I'm going to assign myself to do this.

To those interested, here's my plan:
> This will need to be implemented by overriding the browser's CMD/CTRL-PLUS, CMD/CTRL-MINUS, CMD/CTRL-SHIFT-EQUALS, CMD/CTRL-SHIFT-DASH and CMD/CTRL-mousewheel functionality with our own zoom CSS. Zooming will be simple, our sizing CSS is measured in `EM`s and so all you have to do is set the `font-size` on the body.
> For `PLUS`/`MINUS` you just intercept the `keydown` event, `preventDefault`/`stopPropagation` when the correct keys are down and set a cookie with a new zoom value.
> For `mousewheel` you just intercept the `mousewheel` event, `preventDefault`/`stopPropagation` when the correct keys are down and set a cookie with a new zoom value using the `event` object's `deltaX` to gauge how much you need to add/subtract from the zoom value.

**Comment by justintocci** [comment]
CTRL-Scoll Wheel works on Linux, but I just tried on Mac and it doesn't. Could we get this to work on all platforms please?

**Comment by michaeltocci** [comment]
Yes,

The functionality will be cross-platform because I'm going to have Postage override the browser functionality.

**Comment by michaeltocci** [comment]
Zoom is now handled in Postage and persists across sessions.

Because the implementation is in Javascript, the functionality is cross-platform.

Will be seen in the next release.

**Comment by stevenwinfield** [comment]
Thanks :-)
