### ISSUE TITLE
"About Postage" panel is blank

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#129]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

Tools -> About Postage

...gives me a completely blank popup

![image](https://cloud.githubusercontent.com/assets/1327493/23557722/dbc6399a-0028-11e7-8315-5dda07a3ad3f.png)

Cheers, 
Steve.

**Comment by nunziotocci** [comment]
Do you have a firewall on your network?

That is supposed to be an iframe to https://news.workflowproducts.com/splash/postage.html

**Comment by stevenwinfield** [comment]
Ah - yes, we do.

**Comment by nunziotocci** [comment]
Would it be okay if we put a message saying "Could not load <url>, perhaps you have a firewall?" in the case where we can't connect?

**Comment by michaeltocci** [comment]
I like that idea but let me expand the message text, something like this:

> Couldn't load Postage Version Information & News. If you have a firewall, please open ____________ so you can see information regarding your version of Postage and catch up on the latest news about Postage.
> You can also click this link: https://news.workflowproducts.com/splash/postage.html?app=postage&version=POSTAGEVERSION

**Comment by justintocci** [comment]
Postage Version Information & News could not load. 

(https://news.workflowproducts.com/splash/postage.html?app=postage&version=POSTAGEVERSION)

This may be an issue with your firewall. Do you block SSL-enabled websites?

**Comment by crosstocci** [comment]
Fixed in next release.
