### ISSUE TITLE
Process list is too sparse. 

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#13]
Process list is too sparse. It's hard to find the one you want.

I think I see why you did this, but the query field is limited to a few lines. It should display fine in a table view.

Please convert to table view.

**Comment by michaeltocci** [comment]
The latest version should have the improved process list.

**Comment by justintocci** [comment]
![screen shot 2016-10-05 at 10 44 44 am](https://cloud.githubusercontent.com/assets/14250339/19120613/fd3d90ce-8ae8-11e6-931b-0dad7e240ec8.JPG)

When I select a field in the list I get a sort popup. Please remove the sort popup.

**Comment by justintocci** [comment]
![screen shot 2016-10-05 at 10 56 16 am](https://cloud.githubusercontent.com/assets/14250339/19120957/5ed937b0-8aea-11e6-8ca2-b6f733131424.JPG)

Ok, first off, Kill doesn't kill anything. It runs a PG_CANCEL_BACKEND. So it should probably say "Cancel Backend". 

It also only cancels a process if it's currently active. Make the button clickable only when the backend is active.

**Comment by michaeltocci** [comment]
After doing some research I found out that there are two functions:
1) PG_CANCEL_BACKEND  -  cancels the query for a process
2) PG_TERMINATE_BACKEND  -  kills a process

Here's what I've done:
1) Renamed the "Kill" button to "Cancel"
2) Disabled the cancel button for idle/inactive processes
3) Added a new button for PG_TERMINATE_BACKEND

See below:
![after](https://cloud.githubusercontent.com/assets/10438221/19131831/a0e2638a-8b16-11e6-9bc5-5d519dcdcc6e.png)

These changes will be available in the next release.

**Comment by justintocci** [comment]
please sort the list with the smallest process id at the top

**Comment by michaeltocci** [comment]
Fixed, the change will be available in the next release.

See below:
![after](https://cloud.githubusercontent.com/assets/10438221/19132738/a26440f8-8b1a-11e6-8acf-0dde2c9ff8ea.png)
