### ISSUE TITLE
Shortcut key for EXPLAIN (ANALYZE)

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#130]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

Execute is bound to F5, as it was in pgAdmin, but the EXPLAIN and EXPLAIN ANALYZE functions are not bound to any keys at the moment. Could we have keys for them? In pgAdmin these are F7 and Shift-F7 respectively.

Cheers.

**Comment by crosstocci** [comment]
The keyboard shortcuts have been added in the next release.

**Comment by stevenwinfield** [comment]
Great, thanks!
