### ISSUE TITLE
Activity Statistics graphs don't resize with their window

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#131]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

...leaving me with something like this:

![image](https://cloud.githubusercontent.com/assets/1327493/23558224/aa592956-002a-11e7-985c-e0f844982470.png)

View->Reload resizes the graphs to something more sensible, but then the previously graphed data is lost.

**Comment by michaeltocci** [comment]
Fixed, will no longer be an issue in the next release.

The issue was the width and height was calculated once and we didn't listen to window `resize` to update the width and height.
