### ISSUE TITLE
Set fallback_application_name in connection string?

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#133]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

Just a suggestion:
Users can set application_name in their postage-connections.conf files, but if they don't then it would be nice to at least see "postage" (or something) in pg_stat_activity - setting fallback_application_name (unless the user has set this too) could achieve this.

[Reference](https://www.postgresql.org/docs/current/static/libpq-connect.html)

> fallback_application_name
Specifies a fallback value for the application_name configuration parameter. This value will be used if no value has been given for application_name via a connection parameter or the PGAPPNAME environment variable. Specifying a fallback name is useful in generic utility programs that wish to set a default application name but allow it to be overridden by the user.

**Comment by nunziotocci** [comment]
I have added `fallback_application_name` to the connect code, but I don't see any reason to detect if it is already specified. After all, the Docs say that users should use `application_name`.

Will be seen in next release
