### ISSUE TITLE
Process Manager feature requests

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#139]
The Process Manager provides similar functionality to pgAdmin's server status, but there are a few things I find quite handy in pgAdmin's server status that would be great to see in postage.

Dbadmins here mostly use this to:

- find (and possibly cancel/terminate) queries that are blocking other queries, especially when running DDL as those queries can quickly cause queues of backends waiting for locks.
- identify queries that have been running, or sat idle-in-transaction, for a long time

...so a few things we'd find useful are:
- the ability to sort the table by a particular column, e.g. "State" (to see active/idle-in-transaction queries)
- for the option to have this as a pop-out window, or another tab (though one that is visible while an sql tab is also visible)
- for the window to be resizable. We multiplex our connections using pgBouncer, but we can still have over 100 backends connected at any one time and the current (fixed) window size is a little restrictive at the moment.
- autorefresh

Also, I've noticed a lot of connections marked "Waiting? -> Yes" and "State -> idle". I assumed "Waiting" meant waiting for a lock, but that can't be the case if that backend is idle, so what does it mean?

One other thing that might be useful is the output of [pg_blocking_pids(int)](https://www.postgresql.org/docs/current/static/functions-info.html#FUNCTIONS-INFO-SESSION-TABLE) to show which other backends, if any, are blocking this one. This is only available in postgres 9.6 onwards, though.

Thanks for jumping on these reports so quickly!

**Comment by nunziotocci** [comment]
I made the process manager a tab, we have a plan to open tabs in a new window (see #150)
I added order by dropdowns (one for column, one for direction)
I added autorefresh (defaults to 5 seconds, but you can change it or disable it)

Will be seen in next release.
