### ISSUE TITLE
Incorrect table definition shown

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#140]
If I select a table, like this:

![image](https://cloud.githubusercontent.com/assets/1327493/23611327/904c19ba-026e-11e7-85a6-f3d10e27a1f2.png)

...then a tab on the right is populated with the definitions for that table.
If I now select a _column_ from a different table, like this:

![image](https://cloud.githubusercontent.com/assets/1327493/23611347/b8316606-026e-11e7-8882-263b7f9f51a3.png)

...then the table defintion in the tab still shows the definition of the old table. 

I'd expect either the definition to switch to the selected column's parent table, or (even better :-)) a definition of the column itself, populated with DROP, ALTER TABLE ... ADD COLUMN, and other column-specific stuff, such as that column's statistics target and user-defined number of distinct values.
I don't think there is currently any way of viewing these, is there?

**Comment by crosstocci** [comment]
I've added a new script page for columns:

![screenshot_20170306_143645](https://cloud.githubusercontent.com/assets/24857334/23628683/b7348074-027a-11e7-958a-c5ddf662fdd6.png)

What do you mean by "user-defined number of distinct values"?
I will look into the statistics right now.

**Comment by justintocci** [comment]
Try this:
SELECT null_frac AS "Null Fraction", avg_width AS "Average Width", n_distinct AS "Distinct Values", most_common_vals AS "Most Common Values", most_common_freqs AS "Most Common Frequencies", histogram_bounds AS "Histogram Bounds", correlation AS "Correlation"
  FROM pg_stats
 WHERE schemaname = 'jps'
   AND tablename = 'rjobs'
   AND attname = 'delivertoid'

**Comment by crosstocci** [comment]
Updated script with statistics like pgAdmin's:

```
-- Column: col_key;

-- Null Fraction: 0;
-- Average Width: 11;
-- Distinct Values: 17;
-- Most Common Values:{"Phone Work","Email Work","Phone Mobile","Email Home","Phone Home","Address Home","Address Work",Note,"URL Work","Phone Other","Fax Work"};
-- Most Common Frequencies: {0.182423,0.167776,0.143808,0.123835,0.0745672,0.0679095,0.0652463,0.0625832,0.0359521,0.0346205,0.0173103};
-- Histogram Bounds: {"Address Other","Address Other","Email Other",FaceTime,"URL Home","URL Home"};
-- Correlation: 0.0336667;

-- ALTER TABLE adr.rcard_line DROP COLUMN IF EXISTS col_key;
-- ALTER TABLE adr.rcard_line ADD COLUMN IF NOT EXISTS col_key character varying(150);
-- ALTER TABLE adr.rcard_line ALTER COLUMN col_key SET DATA TYPE <data_type>;
```

**Comment by justintocci** [comment]
actually, all of these should go under the statistics icon.

-- Null Fraction: 0;
-- Average Width: 11;
-- Distinct Values: 17;
-- Most Common Values:{"Phone Work","Email Work","Phone Mobile","Email Home","Phone Home","Address Home","Address Work",Note,"URL Work","Phone Other","Fax Work"};
-- Most Common Frequencies: {0.182423,0.167776,0.143808,0.123835,0.0745672,0.0679095,0.0652463,0.0625832,0.0359521,0.0346205,0.0173103};
-- Histogram Bounds: {"Address Other","Address Other","Email Other",FaceTime,"URL Home","URL Home"};
-- Correlation: 0.0336667;

**Comment by crosstocci** [comment]
Added statistics pane for columns in next release.

**Comment by stevenwinfield** [comment]
That's great - thank you.
