### ISSUE TITLE
Password got from pgpass after failed login?

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#143]
There's a chance that this will be fixed in the next release, when pgpass is used for storing passwords, but just in case not...

On the login screen I specify my username but not password, and hit Log In.
This user has a password, so the login fails, as expected:

![image](https://cloud.githubusercontent.com/assets/1327493/23618671/f8f1f6c8-0288-11e7-9bca-271ca2e55e65.png)

(The escaped quotes and leading colon could be removed here, btw :-))

I hit OK. A line of red text confirms why my last login attempt failed:
![image](https://cloud.githubusercontent.com/assets/1327493/23618748/379bdaba-0289-11e7-8fb7-1ecb0c0e5440.png)

Now I do nothing else but hit "Log In" again - and I'm let in!

The only thing I can think of is that the second time I hit "Log In" the "password" key word wasn't passed as part of the connection string, so libpq [automatically looked it up from my pgpass file:](https://www.postgresql.org/docs/current/static/libpq-pgpass.html)

> The file .pgpass in a user's home directory or the file referenced by PGPASSFILE can contain passwords to be used if the connection requires a password (and no password has been specified otherwise)

The first attempt must have sent an explicit empty string as the password.

**Comment by nunziotocci** [comment]
Fixed, will be seen in next release.

**Comment by stevenwinfield** [comment]
Thanks!
