### ISSUE TITLE
missing a bunch of object types

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#144]
I use this feature constantly. mostly, I select functions, triggers and views to search for code related to a particular column.

Though I don't use it for everything, it's pretty obvious a lot of items are missing. Types for example. We should add in the rest of the items and add a button to select/de-select all checkboxes.

![screen shot 2017-03-06 at 1 06 00 pm](https://cloud.githubusercontent.com/assets/14250339/23625129/b6921d8c-026d-11e7-93b7-f4ff13e2c3d8.JPG)

**Comment by nunziotocci** [comment]
@justintocci I added all of the missing objects Saturday after issue #135 was reported.

There is no select/de-select all checkbox though.

**Comment by justintocci** [comment]
We need that. Currently I have to de-select a bunch of them and it's annoying.

**Comment by crosstocci** [comment]
Added to next release.
