### ISSUE TITLE
Incorrect DROP INDEX script

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#145]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

For example, when an index object is highlighted in the left panel
```
-- Index: log.audit_detail;

-- DROP INDEX log.audit_detail;

CREATE INDEX idx_audit_detail_brin_256 ON log.audit_detail USING brin (table_schema, table_name, id_audit_entry, statement_timestamp, clock_timestamp) WITH (pages_per_range='256');
```

The schema-qualified index name in this case is "log.idx_audit_detail_brin_256", so the first two lines are incorrect.

**Comment by crosstocci** [comment]
The scripts have been fixed in the next release.
