### ISSUE TITLE
Allow manual triggering of autocomplete, or autotriggering after a deletion

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#147]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

For example, in a new SQL tab type:

``SELECT * FROM pu``

Autocomplete should kick in and show "public" as one (perhaps the only) option.
Now if you make a typo, say by hitting "v" instead of "b", the autocomplete helper disappears, and there seems to be no way to get it back without deleting the whole misspelled word and starting again.

It would be great if either:
- I could just delete the errant "v" and use a shortcut key to pop open the autocomplete helper again (e.g. Ctrl-Space is used in a few editors I've used); or
- The autocomplete popup automatically appears after deleting a character, if completions exist.

**Comment by crosstocci** [comment]
The popup now opens when you delete a character.
