### ISSUE TITLE
New toolbar button adjustments

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#149]
First, please make the order, Run, Autocomplete, then the rest.

Also, it feels like if the toolbar background was gray (on a SQL tab, and possibly others), it would be more clear what the buttons apply to.

Also, if I click on a table, the line above the script view is slightly thicker than the line above a SQL tab. I prefer the thicker line.

![screen shot 2017-03-08 at 10 08 47 am](https://cloud.githubusercontent.com/assets/14250339/23712058/4bd32862-03e7-11e7-8f5b-afd0d023a293.JPG)

**Comment by crosstocci** [comment]
Fixed in next release.
