### ISSUE TITLE
Need PGA****4-style charting page

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#15]
I saw the PGA****4-style 'dashboard' tab and it's pretty awesome.

I'd like something like that at some point. We need to come up with a list of important charts.

**Comment by josephtocci** [comment]
Done, will be seen in next version.

![screen shot 2016-11-15 at 4 57 05 pm](https://cloud.githubusercontent.com/assets/14278246/20327849/978aaa6e-ab54-11e6-9d5e-7a3c022dd407.png)
