### ISSUE TITLE
New Feature! Pop a Tab into a new window!

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#150]
This is the last step to solving a lot of UI requests at once.

We want to be able to click a button to cause a SQL tab to open in a new window. In the newly opened window, the object browser should be collapsed since we already have a browser window open.

**Comment by justintocci** [comment]
I think it would be easier to just open a new window and send a query string that collapses the object browser and selects the correct SQL tab. 

Let's just focus on getting it to work and not worry about anything else for now. If we come to want it to behave a certain way let's all settle on what we want before we spend any more time on it.

As soon as it works, please close this issue.

**Comment by nunziotocci** [comment]
Will be seen in next release.
