### ISSUE TITLE
Fix typo in docs/resources

### ISSUE THREAD

**Issue by anthonydb** [workflowproducts/postage#153]
Please correct the spelling of "development" on these lines:

https://github.com/workflowproducts/postage/blob/75633364a3178d91ce9f15dcb8c6a24e4808467f/envelope/app/developer_g/greyspots-1.1.1/documentation/doc-ins-getting-started.html#L52

https://github.com/workflowproducts/postage/blob/482e2c7b87b1a6b12a2c81477e64b01eea8ccd3d/postage/web_root/postage/app/resources/pg-9.2-other.js#L1608

**Comment by nunziotocci** [comment]
The first page is obsolete, from the days when we used fossil inside envelope, I just deleted that one.

The other one will be seen in the next release.

Thank you!

**Comment by anthonydb** [comment]
Just to say I still see this misspelling on the opening splash screen...
![screen shot 2017-03-24 at 9 42 10 am](https://cloud.githubusercontent.com/assets/273891/24299857/e7743752-1080-11e7-861f-6df663c04b3d.png)

**Comment by nunziotocci** [comment]
Fixed!
Thanks for reporting.

**Comment by justintocci** [comment]
could we get a word on how this could have happened?

**Comment by michaeltocci** [comment]
When changing the splash: we copy the html file, make our changes and then replace the old copy.

It's conceivable that someone made a copy to alter the page and then someone else tried to directly change the spelling (without making a copy) and then their fix got clobbered when the new copy replaced the old copy.

To prevent clobbering in the future, we could give the splash page it's own version control. Thoughts?

**Comment by justintocci** [comment]
We should do something. Get with Nunzio and solve this. If making edits directly to the file is a problem then figure out one way to make the changes and prevent all other ways.

**Comment by nunziotocci** [comment]
@justintocci I have put a very hard to ignore comment in the original, and made a copy so this shouldn't regress again.
