### ISSUE TITLE
Shortcut key for new SQL tab

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#154]
Ctrl-T, perhaps? That's what Chrome uses.

**Comment by justintocci** [comment]
That would intercept a request for an actual new tab in the web app version of Postage.

Since CTRL-S is used for "Save Page as", and no one would use that for a Postage page, I think we'd be better off overriding that. "S" for "SQL Tab".

**Comment by crosstocci** [comment]
CTRL-S now adds a new tab.

**Comment by nunziotocci** [comment]
On the desktop we use CTRL-S to save the tab to a file

**Comment by justintocci** [comment]
Drat!

**Comment by justintocci** [comment]
ctrl-O then? "O" for Open?

**Comment by nunziotocci** [comment]
CTRL-O is available.

**Comment by crosstocci** [comment]
CTRL-O  now opens a new tab.
