### ISSUE TITLE
VPN Disconnect causes notification errors and reconnect does not gracefully recover.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#156]
Two related issues here (numbered below). Steps to reproduce:

Start with Electron-desktop version of Postage on a local machine. Connect to a remote network via VPN. Use Postage to log into a remote PostgreSQL server on the VPN network. Disconnect the VPN.

1) At this point you will appear to get 28 Notifications. These are bogus and don't actually exist.

Now reconnect the VPN and attempt to run a SQL command in Postage.

2) You can't run SQL. You also get a console error: { pg-9.2-other.js:2169 // Uncaught TypeError: Cannot read property 'length' of undefined }  I would like to just get back to work but it won't let me.

As a workaround, I can go to the Postage menu > View > and click Reload. This allows me to pick up where I left off. There is no crash since I don't have to log in again at this point.

**Comment by josephtocci** [comment]
Websocket reconnect error is fixed.
The file requests no longer require a database connection.
Websocket error popups adjusted.

Will be seen in next release.
