### ISSUE TITLE
Query error when requesting object properties for a login or group role

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#158]
Windows Server 2008 R2
Postage 3.2.0-beta
Postgres 9.6.2

1. Log in to any database
2. Hide/Show -> enable login and group roles
3. Select any user or group role in the tree on the left
4. Click the Object Properties button

An error message appears:

```
There was an error:

ERROR:  column pg_roles.rolcatupdate does not exist
LINE 27:           (CASE WHEN pg_roles.rolcatupdate   THEN 'Yes' ELSE...
                              ^


ERROR POSITION: 1039
```

``rolcatupdate`` was removed from ``pg_roles`` in PostgreSQL version 9.5 [by this commit](http://www.postgresql-archive.org/pgsql-Remove-rolcatupdate-td5840895.html).

**Comment by crosstocci** [comment]
I have removed the pg_roles.rolcatupdate property when the postgres version is greater than or equal to 9.5.

Also in 9.5 a new property column was added: pg_roles.rolbypassrls.
This property has been added to role properties panels when the postgres version is greater than or equal to 9.5.
