### ISSUE TITLE
Toolbar Buttons

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#160]
The toolbar buttons are differing heights and widths. Also the icons are not centered.

I looked at the CSS, but it is dark magic.

![screen shot 2017-03-20 at 4 12 22 pm](https://cloud.githubusercontent.com/assets/14278246/24121934/07954c52-0d88-11e7-8376-5bfa5b8c371e.png)

**Comment by crosstocci** [comment]
Fixed in next release.
