### ISSUE TITLE
Safari Logout error

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/postage#161]
In the new test suite, we send 100 Logout request in quick succession, but Safari doesn't like it and errors with this message:
```
Failed to load resource: The network connection was lost
```

Since the main way of using Postage is through Electron, this is low priority.

**Comment by josephtocci** [comment]
In here, it says it has to do with keepalive on safari.

Can we make envelope/postage detect safari browsers and disable keepalive for logout?

http://stackoverflow.com/questions/33895463/safari-ajax-request-failed-to-load-resource-the-network-connection-was-lost

**Comment by nunziotocci** [comment]
@josephtocci I am aware that people claim that keep-alive is the culprit, but I made every single http response say `Connection: close` to completely disable keep-alive, and it still isn't working.

**Comment by nunziotocci** [comment]
It works through an nginx proxy, so because there aren't many people who are going to use the webserver on a mac without a proxy is low, I'm closing this issue.
