### ISSUE TITLE
.deb dependencies not listed properly

### ISSUE THREAD

**Issue by stucka** [workflowproducts/postage#162]
The latest .deb package lists only libpq5 as a dependency. This seems to be what you need to get rolling:

libgtk2.0 libgtk2.0:i386 libpq5 libxstst6:i386 libxss1:i386 libconf-2.4:i386 libnss3:i1386

**Comment by nunziotocci** [comment]
May I ask where you got that list? I see in [here](https://github.com/electron-userland/electron-builder/wiki/Options) (search for `depends`) that the default dependencies are:
```
["gconf2", "gconf-service", "libnotify4", "libappindicator1", "libxtst6", "libnss3"]
```
I should have had those before, but I want to know if you just manually resolved runtime errors before I do anything.

**Comment by nunziotocci** [comment]
@stucka What OS are you using? I checked Ubuntu and Debian package registries and I couldn't find `libconf-2.4`.

**Comment by stucka** [comment]
Wow, you're great! I was indeed just manually trying to resolve the runtime errors in Ubuntu 16.04. 

Typo on my end: libgconf-2.4   (missing the "g")

**Comment by nunziotocci** [comment]
Will be fixed in the next release.

**Comment by stucka** [comment]
You are amazing. Thank you.
