### ISSUE TITLE
Make Query Result Columns Only as Wide as Necessary

### ISSUE THREAD

**Issue by anthonydb** [workflowproducts/postage#165]
For readability, it would be nice if the columns in the query result grid displayed only as wide as necessary. For example, I've queried two columns from a table here: 

![screen shot 2017-03-24 at 12 38 17 pm](https://cloud.githubusercontent.com/assets/273891/24304704/b8e4be4c-1090-11e7-82b4-8d5c7ccf2e9b.png)

Note that the two columns spread out across the screen, making it hard to read.

**Comment by josephtocci** [comment]
Michael is working on a new datasheet widget, I think we will add that as a feature. So I am assigning Michael.

**Comment by crosstocci** [comment]
Fixed in next release.
