### ISSUE TITLE
Postage stuck on open a pre-defined connection

### ISSUE THREAD

**Issue by ShaharHD** [workflowproducts/postage#166]
Verified the issue with versions `3.2.0` and `3.2.1`
But with `3.2.0 beta` it works.

Tried to clear `~/.postage/sql' - didn't resolve the issue.

Running on Mac OS

**Comment by nunziotocci** [comment]
Could you elaborate what exactly is stuck? A screenshot would help.

**Comment by justintocci** [comment]
I think he means there is a spinner that gets stuck. Maybe on the login screen?

**Comment by ShaharHD** [comment]
As you can see the screen is empty - not even the welcome page on the right side.
When I hover on the left side - I get this unique blue spinner (which the mac built-in capture ignores as it's the mouse cursor...)

![image](https://cloud.githubusercontent.com/assets/700985/24306103/6dcb244c-10d0-11e7-95d3-a6b029a62d4a.png)

**Comment by ShaharHD** [comment]
I have both `3.2.0 beta` and `3.2.1` installed and both share the same configs in `~/.postage`.

**Comment by nunziotocci** [comment]
Could you take a screenshot of the devtools? `View > Toggle Developer Tools`

**Comment by ShaharHD** [comment]
could this be the cause?
![image](https://cloud.githubusercontent.com/assets/700985/24306327/5054d25e-10d1-11e7-8753-3ce1b0b203d6.png)

**Comment by ShaharHD** [comment]
I don't get this error on 3.2.0 beta

**Comment by nunziotocci** [comment]
This seems to be the caching issue that we had fixed with 3.2.1.
Do you have postage 3.2.0 beta running at the same time as 3.2.1? I think that might mess up 3.2.1

**Comment by ShaharHD** [comment]
not at the same time, I close one and open the other. they are different apps on my mac.
how do I clean the cache then?
![image](https://cloud.githubusercontent.com/assets/700985/24306476/cf9b6ea6-10d1-11e7-8525-2378aa3f7f27.png)

**Comment by ShaharHD** [comment]
When I 1st installed 3.2.1, I choose to overwrite the `Postage.app` - I only renamed and reverted to beta once I realized 3.2.0 and 3.2.1 broke something on my system :)

**Comment by nunziotocci** [comment]
To clear the cache, all you have to do is `View > Reload` or `Cmd+R`

But before you do that, I would like a screenshot of the network pane of the devtools, that would help a more thorough investigation.

**Comment by josephtocci** [comment]
I reaffirm my comments in a previous conversation that we should find out how nginx handles the 304 response code and compare it to what we are doing. I am looking up the code now.

**Comment by ShaharHD** [comment]
Before Reload:
![image](https://cloud.githubusercontent.com/assets/700985/24306679/74e6e3c2-10d2-11e7-9fc7-01cc66811682.png)

Reload didn't change anything.
I can try to "clear storage" in application ... but I'm guessing you want me to continue testing without doing so.

**Comment by nunziotocci** [comment]
It says `(from disk cache)`, that's all I needed to know. To invalidate the cache, check the disable cache checkbox and refresh. Then you can continue using Postage normally.

**Comment by josephtocci** [comment]
It seems that this is an electron caching issue, not the C code. Regardless, I have found the nginx code to compare to. We should at least look at it and make sure we are at least as careful as nginx.

Nginx has a BSD 2 Clause license, and the relevant function is at:
https://github.com/nginx/nginx/blob/f8a9d528df92c7634088e575e5c3d63a1d4ab8ea/src/http/modules/ngx_http_not_modified_filter_module.c#L136

**Comment by nunziotocci** [comment]
@josephtocci I have looked and we are just as strict as nginx.

This is all on me, I forgot to push a change last night when I was releasing 3.2.1, so we will get right on it and have a release out later today (say 3:30-4:00PM CDT).

You can still use postage if you disable the cache and refresh.

**Comment by ShaharHD** [comment]
hi.

Disable cache resolved the issue.

Thanks

**Comment by ShaharHD** [comment]
Interesting ... I need to run the disable cache for every connection in my connection list.

**Comment by nunziotocci** [comment]
@ShaharHD That's because each connection has a unique URL that gets cached separately.

**Comment by nunziotocci** [comment]
@ShaharHD [We have a new release out](https://github.com/workflowproducts/postage/releases/tag/eV3.2.2)
