### ISSUE TITLE
Keyboard shortcut options

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#167]
Reddit user billrobertson42 had a request:
https://www.reddit.com/r/PostgreSQL/comments/6177m0/free_open_source_pgadmin_replacement_postage_has/dfe418c/

> Is there an option to change the key command to run a query? f5 is too far out of the home row for my tastes.

We currently have a page with explanations of some of our shortcuts, but not all of them.
1: Add documentation of all the shortcuts to the documentation page we already have. @crosstocci

2: Add options to our Postage settings page for shortcuts.

If f5 is out of range then we need the settings to be able to handle the Shift, Control, Option and Command keys. We need to research this and come up with a way of making both the Mac users happy with Command-keys and the Windows users happy with Control-keys. I don't know how to make Linux users happy. @nunziotocci can you weigh in on Linux?

**Comment by nunziotocci** [comment]
In general, Linux uses Control like windows.

**Comment by Tostino** [comment]
I'd just like to add my support for user-settable shortcuts for all shortcuts.  Why hard code when having a sane default with the option to change isn't too much more work.  That's my opinion at least.

**Comment by justintocci** [comment]
@tostino, my understanding is that Cross is almost done. Thank you for your input!

**Comment by crosstocci** [comment]
The keyboard shortcuts are now configurable under: "Tools>Postage Options".

![screenshot_123456789123456789](https://cloud.githubusercontent.com/assets/24857334/24415076/e2ec6b82-13a5-11e7-9dec-7e403a894629.png)
