### ISSUE TITLE
Autocomplete screws up cursor on rare occasions

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#168]
![screen shot 2017-03-25 at 10 14 44 am](https://cloud.githubusercontent.com/assets/14278246/24323480/faab6eda-1143-11e7-94d3-3aeeef74fccf.png)

To reproduce:
1: From where the cursor is, type ".cr"
2: Press tab to autocomplete.
3: Press the up or down arrow. It will not move to the next line but left-right works.

![screen shot 2017-03-25 at 10 14 51 am](https://cloud.githubusercontent.com/assets/14278246/24323788/119320c0-1149-11e7-9af8-0a7dabf889ec.png)

Workaround is to reload.

**Comment by crosstocci** [comment]
Fixed in next release.
