### ISSUE TITLE
If nothing is selected, run should mean run the query under the cursor.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#171]
Apparently, SQLDeveloper by Oracle does not run an entire script when there is no selection.

Instead, it runs the query under the cursor.

Posted for billrobertson42 via reddit

**Comment by nunziotocci** [comment]
I think this should be an option, but probably not the default because PgAdmin.
 runs the whole script.

Also, I have always had F5 run the whole script and I don't want to get accustomed to something else.

**Comment by josephtocci** [comment]
@nunziotocci Well this is for Postgresql, so the default should be what Postgresql people expect. But we also want to accommodate Oracle users switching to Postgresql.

@justintocci I think we can take this a little further by having Ace highlight the query that will run. But we should only do that when this mode is active.

Perhaps we should also have a key to quickly switch this option without going into the Postage options. I feel like this is more of a runtime option instead of something you set up and then forget about. Once I have the results panel formatting the way I want it, then I want it to stay like that. But I wouldn't want this feature always on. So maybe a quickkey to switch between normal and Oracle mode. Just an idea.

**Comment by justintocci** [comment]
We need default behaviour that will be acceptable to everyone. I wish there was an obvious answer, like F6, but we can't do that because I'd be afraid of users accidentally hitting F5.

**How about this:**
F5 w/selection runs selection
F5 w/o selection runs entire script
F2 w/selection runs selection
F2 w/o selection runs query under cursor

**Comment by josephtocci** [comment]
Could we have billrobertson42 weigh in? He's the one who suggested it and thus probably actually used the software so let's ask him.

**Comment by justintocci** [comment]
@josephtocci, I agree. We should shade the query being run and then fade it out for clarity. We don't want to change the cursor location though.

**Comment by billrobertson42** [comment]
If you had two different run commands such as...

1) run current query (query under cursor or if cursor is just past a query, that one)
2) run entire buffer

You could assigned ctrl-enter to the first one by default, it would work just like SQLDeveloper. Then you could assign the second one to ctrl-e, you would satisfy both sets of users w/something natural to what they're accustomed to using.

User configurable key bindings would go well with this too.

**Comment by justintocci** [comment]
We already opened and issue for configurable key bindings. We're going to try to do that: https://github.com/workflowproducts/postage/issues/167

**How about this:**
[CTRL]-[E] or [F5] or [CTRL]-[RETURN] w/ selection runs selection
[CTRL]-[E] or [F5] w/o selection runs entire script
[CTRL]-[RETURN] w/o selection runs query under cursor

Does that seem correct?

**Comment by billrobertson42** [comment]
Yeah, that sounds awesome! The only thing I would add is that "query under cursor" also means query right before the cursor. e.g. I've typed in the query and a semi-colon and I hit ctrl-return and it runs the query that I just finished, even though technically it's not under the cursor.

**Comment by justintocci** [comment]
Ok, from what you wrote, the character right after the semicolon is still part of Q1. The next character is Q2. Here is my understanding:

```
SELECT 'test1';_ <= cursor here is Q1
_SELECT 'test2';
^cursor here is Q2
```
And, the case where there are multiple spaces after the query:

```
SELECT 'test1';_       _<= cursor here is Q2
               ^cursor here is Q1
SELECT 'test2';
```

I'm just trying to be clear. I can't make any promises at this point. The code to split on semicolons is complex. But I think there may be a shortcut where we can make this happen if I'm understanding it correctly.

**Comment by justintocci** [comment]
Ok, I have a new question for @billrobertson42. 

Let's say we are writing a FUNCTION and inside the body we type a SELECT query. Does the `[CTRL]-[RETURN]` execute the entire FUNCTION or just the SELECT? 

We have a choice at this point to code this in one of two ways:
1) load the entire script, split on semicolons, run the query where the cursor is located.
2) start with the location of the cursor and work backwards until you find a viable query and run that.

The autocomplete code uses process #2 but there is a bug in it. https://github.com/workflowproducts/postage/issues/179

While we're fixing that, we have time to decide which way to go. After some discussion we've decided we're going to do #2.

Reasons in reverse order of importance:
1) we already have code for #2 
2) it will be faster than #1 
3) it will be easier to see what query is running (less likely the query runs off the page)
4) it will take less cognitive load to know what query is about to run 
5) it will take less cognitive load to think about what the consequences of the query running will be.

If the community would like to contribute some advice then now is the time. We could start on this very soon.

**Comment by billrobertson42** [comment]
If you want, I can see what SQLDeveloper would do in the middle of a function. Either way you go though I think will be fine. It might surprise people if it doesn't try to create the function at first, but I think they'll adapt, and I would wager that most people spend less time writing functions.

As to the question from a few days ago (sorry I missed it - I was driving). I'm not sure if it's "just past" the semi-colon or on the same line.

I will follow up in a bit once I have a chance to see what SQLDeveloper does. I'm not suggesting you should take it as gospel, but having the data point should help you come to a decision.

**Comment by billrobertson42** [comment]
Would method number two work in the presence of a CTE?

e.g.

    with foo as (
        select * from blah
    )
    select * 
    from bar
    join foo using(baz);

Would that just scan backwards to the select and then fail to run? That would be frustrating.

Note, the SQLDeveloper does not work correctly if the query preceding the one you're editing when you hit ctrl-enter is not terminated by a semi-colon.

**Comment by justintocci** [comment]
> Would that just scan backwards to the select and then fail to run? That would be frustrating.

Yes, method number two would work that way. If you were in the first select it would run that, if you were in the second select it would run that. To get the With to run you'd need to be between the 'with' and the open parenthesis.

I'll take your comment that working in that way would be frustrating to be a vote for method one.

The advantages of #1 are:
1) that it would run a FUNCTION, VIEW or WITH if that is where you are. 
2) if you want to run a local query it would be easier to select than having to select a F, V or W.
3) Queries inside Fs tend to use variables and are less likely to run (and consequently be run).
4) Queries inside Vs and W's often have too many records to run directly. You use WHERE clauses on Vs and Ws to tame them. That's usually done in a query that calls the V or W.

This is frustrating exercise. There are good points on both sides. I think I've changed my mind three times now. Right now I'm leaning toward #1.

**Comment by crosstocci** [comment]
Option #1 will be implemented in the next release.

**Comment by billrobertson42** [comment]
Sorry for the delay, I took some time in SQLDeveloper to test how the ctrl-enter function works as data points.

If you're on the same line as a query, but past the end of the query, it will execute the query that ends on that line when you hit ctrl-enter.

If you're on an empty line, it will execute the next query.

**Comment by justintocci** [comment]
Drat. We just did a release and it works such that the character after a semicolon runs the previous query but everything after that is the next query.

Anyway, give it a try and if you hate it re-open this issue and we'll look at it.

**Comment by billrobertson42** [comment]
I think it's absolutely awesome either way. Thanks!
