### ISSUE TITLE
No scroll bar on dependency list

### ISSUE THREAD

**Issue by Tostino** [workflowproducts/postage#172]
When viewing a dependency list for a tablespace, if the list is longer than the screen, no scroll bar appears.  Not sure if this happens on other dependency lists or not, only tried on table space so far.

Example: 
![image](https://cloud.githubusercontent.com/assets/8227578/24386719/1b686630-133f-11e7-953e-cb588b79992e.png)

**Comment by crosstocci** [comment]
Fixed in next release.
