### ISSUE TITLE
Design Table is broken

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#175]
tried to reorder columns, didn't work

**Comment by josephtocci** [comment]
It worked for me, what table, and what columns?

**Comment by justintocci** [comment]
db ss > schema test > asdf2 > reorder the columns > click generate script

it says it's loading but never completes.

**Comment by josephtocci** [comment]
It had to do with a rule. I now have Postage error every time this happens, and I have fixed the rule for your particular case. Will be seen in next release.
