### ISSUE TITLE
Cannot do an unattended install into a custom directory

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#177]
Postage 3.2.1
Windows Server 2008 R2

Our IT department are testing unattended deployment of postage to many windows boxes, but have hit a snag.
The installer seems to be using NSIS, and they can successfully use the "silent" switch (/S) but they are unable to install for anyone but the current user - not all users, as is required.
They are attempting to use NSIS's /D switch for this - /D=C:\Program Files\Postage - but it seems to be ignored.

Any thoughts?
Thanks,
Steve.

**Comment by nunziotocci** [comment]
@stevenwinfield We don't use NSIS directly, so I don't know why it isn't respecting `/D`. But I did find electron-userland/electron-builder#845 so I want you to try `/allusers` instead of `/D`. I tested it and it worked for me, let me know how it goes.

**Comment by nunziotocci** [comment]
@stevenwinfield Any word on this?

**Comment by stevenwinfield** [comment]
Not yet, I'm afraid - our IT guys were a bit snowed under last week. I'll try to get it tested early next week.

**Comment by stevenwinfield** [comment]
We've just tested it and it works fine, thanks.

Is there any way to get a list of valid command-line switches for the installer? Using "/?" just begins the installation process, and using a 3rd-party tool to guess the type of the installer lead us to believe it was an NSIS one, which turned out to be false.
Our IT guys were looking, for example, for a way to disable the creation of desktop shortcuts.

Thanks!

**Comment by nunziotocci** [comment]
It is an NSIS installer, but I am not building it directly. I am using [electron-builder](https://github.com/electron-userland/electron-builder) to build all of my packages.

It looks like the only options are /allusers and /currentuser. I will look into adding an option for the desktop shortcut.
Do you need any other options?

**Comment by nunziotocci** [comment]
@stevenwinfield There will be an argument to disable the desktop shortcut in the next release.

**Comment by stevenwinfield** [comment]
(Sorry - I could have sworn I added this comment a few hours ago)

We were also looking for a way to specify the installation directory, in particular so that we could install in a directory that doesn't include the version number. Our IT guys maintain their own shortcuts to Postage, and  ideally they would continue to work after an upgrade.

Also a  /? switch to show what other switches are available, or at least a link to where this information can be found. The installation process definitely shouldn't start if /? is given!

Thanks

**Comment by justintocci** [comment]
I think there is value in allowing the switch, so let's do it, but Is it useful for us to put postage in a folder with the version number? If we don't need it for some reason, maybe we could discard that.

I am also wondering why we no longer install in the Workflow Products folder.

**Comment by nunziotocci** [comment]
@justintocci We don't need it in the version number folder, but electron-builder might require it. I am checking now.
Also, we aren't installing in the Workflow Products folder because when we started using electron, I forgot to tell it to do so.

**Comment by nunziotocci** [comment]
@stevenwinfield @justintocci The version number is not supposed to be there. It was removed from electron-builder recently, but, I apparently built the latest installer with an older version of electron-builder.
Related: electron-userland/electron-builder#1435

**Comment by justintocci** [comment]
Let's get this closed. Here are the issues as I see them:

1) /? should give some kind of help, not start the install process.
2) install to the Workflow Products folder (give workaround if necessary)
3) add the desktop shortcut option

**Comment by nunziotocci** [comment]
@stevenwinfield @justintocci As a workaround, you can uninstall postage and delete the install directory, then reinstall and the version number folder will not be created

Also, I added a `--no-desktop-shortcut` option to the installer (the electron-builder project asked that I use the linux argument style).

**Comment by stevenwinfield** [comment]
Thanks. --no-desktop-shortcut, and specifying installing for all users works fine.
It's a bit weird having to use both /windows and --linux style switches, but never mind.

/? still launches the installer, rather than giving any help.

**Comment by nunziotocci** [comment]
@stevenwinfield I have researched adding a help option, but it apears that NSIS has no reliable way to print to the console. I could open a messagebox instead, but that would be confusing.

@justintocci Thoughts?

**Comment by justintocci** [comment]
> but it appears that NSIS has no reliable way to print to the console

That doesn't seem right. Don't other programs print to the console? A simple printf should work shouldn't it?

**Comment by nunziotocci** [comment]
@justintocci NSIS installers are GUI programs, which means that even when launched via command line, they aren't associated with a console. I tried some code to attach to the parent console, but even that didn't work. I could open a messagebox with the options in it, but I think that would be confusing.

**Comment by justintocci** [comment]
ok, i did some research. chrome has many switches but none of them print to stdout in the cmd window on windows. 
I don't see a way to make it print to the command line and I don't see chrome doing it.

@stevenwinfield let us know if you know of a gui app that does this and we'll see what we can do.

Meanwhile, what would you prefer we do when we encounter "/?"
1)  just quit 
2) ignore it (what we do now)
3) add a messagebox with some help and quit when they click ok.

**Comment by justintocci** [comment]
We have no preference here for any particular functionality. Since we can't provide what the user is asking for we're going to close this until we get a suggestion that we can implement or at least a hint as to how to do what we're being asked to do.
