### ISSUE TITLE
Capital DB name breaks

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/postage#178]
Via @Vonatzki from #59

Hi, just stumbled upon this simple and wonderful application from your Reddit thread! Somewhat of a newbie postgresql user here.

Our database is using LATIN-1 encoding. Whenever I try to log in to the database, it causes an error:

There has been an error with the Database connection.

>....\db_framework_pq\db_framework.c:escape_conninfo_value: escape_conninfo_value: strlen = 0
>Connect failed: FATAL: database "scv" does not exist
Is it due to our database encoding? Though I have a gut feeling that this is caused by our database name being capitalized (name is "SCV"). As shown, error dialog returns "scv" instead of "SCV".

Trying to get into 'template_01' and 'postgres' dummy databases works out just fine.

Thanks! So far I'm loving the interface! Apologies if I posted on the wrong issue. Not quite sure if this is encoding-related, really.

**Comment by nunziotocci** [comment]
Will be seen in next release.

**Comment by Vonatzki** [comment]
Thank you for the quick response!

Somehow, I knew it was caused by my all-caps database name. I know it's bad practice when naming databases. So sorry for the inconvenience.

Cheers!

**Comment by michaeltocci** [comment]
No worries at all! We're glad you let us know.

Thanks!
