### ISSUE TITLE
"Edit Configuration" button should be under Electron shell's "File" menu 

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#18]
Please add "Edit Configuration" as an item under the Electron shell's "File" menu (top left of header bar, or in Windows, at the top left of the main window), then remove the "Edit Configuration" button from the login screen. 

The "Edit Configuration" is not able to be used in the web version. Since we have the opportunity, it would be better to leave the web version alone and include the "Edit Configuration" button in the Electron interface.

This way we don't have code in the web version that is only useful for the Electron version.
![screen shot 2016-10-11 at 2 41 41 pm](https://cloud.githubusercontent.com/assets/14250339/19285932/9e0f0abe-8fc1-11e6-8825-2daeec3c0a3c.JPG)

**Comment by nunziotocci** [comment]
@justintocci 

How does this look?

![capture](https://cloud.githubusercontent.com/assets/7560749/19316559/8deaaade-9067-11e6-81a9-7b945e8bf046.PNG)

Is there a specific keyboard shortcut you would like me to add?

**Comment by justintocci** [comment]
That is 1000 times better than what I asked for, thank you.

I don't have any suggestions for keyboard shortcuts. I suggest you implement without and we'll let the community make a request.
