### ISSUE TITLE
More obvious current user information

### ISSUE THREAD

**Issue by clomdd** [workflowproducts/postage#180]
Hi,

It would be really useful to have the current user displayed somewhere in the database connection info in the top left of the window. I know you can get the connection info pane up which displays this, but when working on testing with two different users on the same database it's easy to get the windows confused.

Not exactly urgent, just a nice to have!

Thanks,
Chloe

**Comment by justintocci** [comment]
![screen shot 2017-03-30 at 10 45 06 am](https://cloud.githubusercontent.com/assets/14250339/24513090/f5dd21e6-1535-11e7-94aa-f0eb4295710b.JPG)

how about:

`postgres@sunnyserve(user_name)`

**Comment by clomdd** [comment]
That sounds great to me! Thanks for picking this up :)

**Comment by crosstocci** [comment]
Fixed  in next release.
