### ISSUE TITLE
in SQL tab, while editing a script, I lose the ability to [TAB] or use up and down arrows

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#182]
in SQL tab, while editing a script, I lose the ability to [TAB] or use up and down arrows

If i reload, then it goes away for a while, but then it comes back.

Cross says this should have been fixed a while ago, and that I may have a cached file. I'm on Electron on Windows, Postage 3.2.2. If it is a cache issue it would be cool to get a button that would clear it. 'reload' in the View menu doesn't do it.

**Comment by nunziotocci** [comment]
Caching is not an issue on 3.2.2, it is cleared every time it is launched.
It is probably just another edge case that needs to be fixed.

**Comment by josephtocci** [comment]
I could've sworn this was fixed and not released yet. Does it happen on the development version?

**Comment by justintocci** [comment]
it happens so often on the windows version now that i want to move up the next release as soon as possible. but only if it's going to be fixed.

**Comment by crosstocci** [comment]
This was fixed a day after the last release, so this won't be fixed until the next version is out.

**Comment by nunziotocci** [comment]
I have determined the commit that fixed it is 9738fdd and it wasn't in 3.2.2 but we will be releasing again soon and this commit will be included.
