### ISSUE TITLE
Triangle Icons are not the same size

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#185]
![screen shot 2017-03-31 at 1 31 52 pm](https://cloud.githubusercontent.com/assets/14278246/24565180/b4599918-1619-11e7-81cd-13940e9f14be.png)

**Comment by justintocci** [comment]
I'm confused. They look the same to me.

**Comment by josephtocci** [comment]
The arrows pointing down are not the same size as those pointing right. It is really obvious on my screen.

**Comment by justintocci** [comment]
your screen shot only shows arrows pointing down, so it doesn't illustrate the problem.

We fixed this a while back for a certain browser/OS combination, consult Cross for details. He should be able to add your combination to the fix.

**Comment by josephtocci** [comment]
Functions and Sequences in my screen shot do have arrows pointing right. They are just so small they look like dots.

**Comment by justintocci** [comment]
hah! I totally missed them because they are so small.
