### ISSUE TITLE
Can not move carat with up and down arrows in query editor

### ISSUE THREAD

**Issue by Tostino** [workflowproducts/postage#186]
Just wanted to report that occasionally I am not able to move the carat up and down a line with the arrow keys unless I go left or right all the way to beginning or end of a line.  Up and down do not work.

I cannot determine what is causing this, because it's not every time.

**Comment by josephtocci** [comment]
This is issue #168, which was closed. Reload the page as a workaround.

**Comment by Tostino** [comment]
Sorry, should have searched better before creating an issue.  Appreciate it.
