### ISSUE TITLE
Change 'Stop Socket' to 'Stop Loading' or something similar.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#188]
![screen shot 2017-03-31 at 3 55 08 pm](https://cloud.githubusercontent.com/assets/14250339/24569156/732c95b0-162a-11e7-96d5-fa5e83c1df26.JPG)

I think the word 'socket' is not really something users should need to understand.

**Comment by crosstocci** [comment]
Fixed in next release.
