### ISSUE TITLE
Explain Needs a better error when the query does not start with select

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#190]
Postgresql has a misleading error when you try to explain a `CREATE OR REPLACE VIEW`. Since this is not a select query, the explain doesn't work. We should check the query and if it does not start with select, and it errors, also display our own message like:
> Explain queries only work on SELECT

Or something similar.

**Comment by justintocci** [comment]
wouldn't it be more appropriate to just report this to the postgres team?

**Comment by crosstocci** [comment]
I checked on Postgresql 9.6.2 and the errors are still not describing the actual problem.

**Comment by nunziotocci** [comment]
This doesn't seem like something we need to be mointoring as an issue. So, I'm just going to close it.
