### ISSUE TITLE
Want to run psql-style COPY from SQL tab

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#195]
Our SQL tabs will choke on the following script:

```
COPY test.asdf (asdf_1, asdf_2) FROM STDIN;
AF  AFGHANISTAN
AL  ALBANIA
DZ  ALGERIA
ZM  ZAMBIA
ZW  ZIMBABWE
\.
SELECT current_date;
```

This is because we're not detecting a STDIN situation and switching contexts. We need to re-work SQL split to only pull one query at a time, then, if PostgreSQL says that a COPY was detected and it wants STDIN data then we need to feed it the data until we detect a "\\." alone on a line. Then we switch back to a normal SQL transaction context and feed the next query.

**Comment by nunziotocci** [comment]
We don't have the resources for this right now. We'll look at this again in a couple of months.
