### ISSUE TITLE
Provide Separate Boxes for Host, Port, etc. on Login Page

### ISSUE THREAD

**Issue by anthonydb** [workflowproducts/postage#2]
Rather than having the user edit a string of variables to provide host, port, server name and other info to connect to a database, make each of those values a text box. That way, it's faster to click in one, fill out the info, and tab to the next. Currently, I find myself mousing into the point of the string several times where I need to insert values.
![screen shot 2016-09-20 at 1 22 49 pm](https://cloud.githubusercontent.com/assets/273891/18681422/faa6f288-7f35-11e6-862f-dfe695b9378b.png)

**Comment by michaeltocci** [comment]
Thanks for the suggestion.

You're correct, I'll split it out into multiple boxes for easier typing.

The fix should be included in the next Saturday release.

**Comment by michaeltocci** [comment]
The fix will be included in the next release.
