### ISSUE TITLE
When I click RUN button on selected SQL, then click [DELETE], nothing happens

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#202]
It would appear that clicking the RUN button causes the ACE Editor to lose focus.

Steps to reproduce:

Type in SQL. 
Select the query so it's blue.
Click the RUN button (right pointing triangle) with the mouse
Click [DELETE]
nothing happens

Expected behavior would be for the selected query to be deleted.

**Comment by nunziotocci** [comment]
Will be seen in next release.
