### ISSUE TITLE
Buttons clash in PGPASS editor window

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#203]
Postage 3.2.3
Windows Server 2008 R2

The "PGPASS Documentation" and "Reload Postage" buttons clash with each other and the window border - for me, at least:

![image](https://cloud.githubusercontent.com/assets/1327493/24910189/e9bde58e-1ebe-11e7-8c1a-612aa8dabfd2.png)

**Comment by nunziotocci** [comment]
Will be seen in the next release.
