### ISSUE TITLE
Constraint Triggers displayed twice in object tree

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#204]
Postage 3.2.3

I'm not sure if this was a conscious decision or not, but user-defined constraint triggers appear under both the "Constraints" and "Triggers" nodes in the object tree.

**Comment by justintocci** [comment]
@crosstocci see what PG Admin does and let's do that.

**Comment by nunziotocci** [comment]
PGAdmin shows them under triggers

**Comment by crosstocci** [comment]
Changed tree view to only display constraint triggers in triggers.
