### ISSUE TITLE
Error when editing a cell in "Edit data" tab

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#206]
Postage 3.2.3
Postgres 9.6.2
Windows 2008 R2

I select a table, hit Edit data, click in a cell and edit its contents, and press return:

![image](https://cloud.githubusercontent.com/assets/1327493/24912154/35b57302-1ec5-11e7-99ce-0f433014fca7.png)

...so apparently there was an error :-)
The Full Error Text is empty:

![image](https://cloud.githubusercontent.com/assets/1327493/24912279/93d96c86-1ec5-11e7-92a1-1909996e02f8.png)

...but the console log does contain this:

GS.removeLoader Error: loader not found
GS.removeLoader @ greyspots.js:10565

**Comment by nunziotocci** [comment]
I can't seem to replicate this, does it happen every time? I tried 3.2.3 and 3.2.6
Also, we've release three new version since 3.2.3, could you try 3.2.6?

**Comment by stevenwinfield** [comment]
I think this is reproducible in 3.2.12, and is duplicated in https://github.com/workflowproducts/postage/issues/268 - it seems only tables in the public schema are affected.

**Comment by crosstocci** [comment]
@stevenwinfield is this still a problem in 3.2.13 and later?

**Comment by stevenwinfield** [comment]
I'll let you know once we've upgraded.
Thanks.

**Comment by justintocci** [comment]
I'm going to close this. Anyone can re-open if the problem re-appears.
