### ISSUE TITLE
Dropping a schema while the schema is selected in the treeview

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#207]
Dropping a schema while the schema is selected in the treeview causes a perpetual loader.

![screen shot 2017-04-17 at 10 44 46 am](https://cloud.githubusercontent.com/assets/14278246/25094055/f0214fba-235a-11e7-8f76-4867a23093e9.png)

**Comment by crosstocci** [comment]
Could not reproduce on the latest version you might need to update postage.
