### ISSUE TITLE
Autocomplete is not working properly.

### ISSUE THREAD

**Issue by crosstocci** [workflowproducts/postage#214]
It needs a major restructure and clean up.

**Comment by justintocci** [comment]
I'm really regretting bragging about autocomplete. 

> We have autocomplete! We have autocomplete! 
>-- total moron

Right now we have a teaser. You type one letter and it shows the drop down, then you type another and it goes away.

**Comment by crosstocci** [comment]
The autocomplete logic and opening/closing code has been restructured.
The binding and unbinding code has been made much more reliable now.

Will be seen in the next release.

If anyone finds a autocomplete issue please open an new issue for it.
