### ISSUE TITLE
Autocomplete doesn't play well with find/replace

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#222]
Immediately after a find and replace, click somewhere. If you do it right, it starts appearing and disappearing. I think the find and replace inadvertently calls an autocomplete function.

![screen shot 2017-04-26 at 12 53 04 pm](https://cloud.githubusercontent.com/assets/14278246/25448838/6d173c7a-2a7f-11e7-96e1-c54b1cdcdf66.png)

**Comment by josephtocci** [comment]
Fine/replace doesn't replace all when this happens, it only does some of the places to find. Find/replace all is broken until we get this fixed.

**Comment by crosstocci** [comment]
Fixed in next release.
