### ISSUE TITLE
Autocomplete can't insert to multiple cursors

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/postage#224]
When I have multiple cursors and try to type something in, it stops after the first character. Then I can't click 
 anywhere except for in the dropdown (even if I do close it by selecting something). And it only autocompletes the first cursor.

**Comment by crosstocci** [comment]
Fixed in next release, however I would like to keep this issue open because the new autocomplete can't insert to multiple cursors yet.

**Comment by crosstocci** [comment]
Fixed in next release.
