### ISSUE TITLE
Autocomplete not sorting alpha, two tables with same name (different schemas)

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#229]
![screen shot 2017-05-01 at 10 07 05 am](https://cloud.githubusercontent.com/assets/14250339/25583169/3cbcb174-2e56-11e7-9b6e-b06326ccc3f9.JPG)

So I have the same table name showing up twice. Once for the usr schema and once for the tra schema. I'd prefer each table name only show up one time. This would also remove the out-of-order sorting.

**Comment by crosstocci** [comment]
Fixed in next release.
