### ISSUE TITLE
Text selection does not dismiss autocomplete dropdown. 

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#232]
![screen shot 2017-05-01 at 4 15 09 pm](https://cloud.githubusercontent.com/assets/14250339/25595165/67bf6c12-2e89-11e7-8d11-bebe323bcf0e.JPG)

If I hold down shift and use the arrow keys to make a text selection, the autocomplete dropdown should be dismissed.

**Comment by crosstocci** [comment]
Fixed in next release.
