### ISSUE TITLE
Find in a long script, click next or previous button, doesn't give feedback

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#239]
when using find in a long script, click next or previous button.

I would expect the button to shade or otherwise look like I clicked it. But it doesn't give any feedback. Since there is no immediate return of a found item, I'm left thinking I misclicked, so I click again. Then it searches again immediately. If the next result was found very quickly, I've skipped a result and there was no indication given.

**Comment by justintocci** [comment]
actually, there is no feedback given even in a short script. This should be fixed for all cases so when you click a button you see it was clicked.

**Comment by crosstocci** [comment]
Will be seen in .12
