### ISSUE TITLE
Object CREATE scripts need work

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#240]
Currently, the way the scripts are written, it's difficult to separate say the CREATE code from the commented section with the INSERT, UPDATE, DELETE and SELECT.

If someone could clean up this code we could selectively turn off the comments for things like, when you open a tab based on a script. Also, when you are dumping a schema to a script.

**Comment by crosstocci** [comment]
@justintocci is this acceptable?

```
-- UTILITIES:

/*
-- BEGIN SELECT
SELECT column
  FROM test.asdf;
-- END SELECT

-- BEGIN INSERT
INSERT INTO test.asdf
            (column)
     VALUES (column);
-- END INSERT

-- BEGIN UPDATE
UPDATE test.asdf
   SET column = new.column
-- END UPDATE

-- BEGIN DELETE
DELETE FROM test.asdf
      WHERE -CONDITIONS-;
-- END DELETE
*/
```

**Comment by crosstocci** [comment]
Fixed in next release.
