### ISSUE TITLE
Object Browser vertical scroll bar stops working.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#242]
Steps to reproduce:

Open objects in the object browser enough to get the scroll bar to appear.
scroll down to the bottom.
click any down triangle to make it close. (for example, close an open table or column list)
At this point you have a scroll bar with room to move up. Don't drag it up, that works fine. Instead, click in the scroll track above the scroll bar. I have attached a picture of where to click.

Expected behavior would be for the object browser to move to the top. Instead, the scroll bar moves up but nothing happens to the object browser. 

![screen shot 2017-05-04 at 3 57 50 pm](https://cloud.githubusercontent.com/assets/14250339/25724773/b4e1e28a-30e2-11e7-8a90-2d185c516f80.JPG)

**Comment by crosstocci** [comment]
It appears that this is only an issue on electron builds so it may be a chromium issue.
Please update chromium in the next release, maybe that will fix it.

**Comment by justintocci** [comment]
I think what you mean is we'll get (i expect) a chromium update with the next Electron build.
