### ISSUE TITLE
Possible issue, need to test race condition

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#243]
This is apparently an issue with official clients and a potential Postage user was asking me if we were susceptible to the same problem. I told him I didn't know but from his explanation it is likely. Therefore, we'd look into it.

I heard about this issue a couple days ago and haven't had time to test it so I'm going to record it here to prevent me from forgetting about it.

Set up:
Two Postage instances on two computers connected to the same database. 
In Postage one, start adding columns to a table. Unclear whether it involves adding one column per transaction.
In Postage two, refresh the object browser. At some point it should freeze. You've created an open query that will never complete.

Why:
Apparently, the PG Catalog is (or at least was) susceptible to a situation where a column is added but not completely, yet said column is not invisible to other transactions. 

Resolution:
If this is a problem then we need to figure out a safe way to read from PG Catalog. If not then maybe the info is just about older versions of Postgres. I'm confused that the PG Catalog is not protected from this like regular tables are. I meant to research it before I posted it but I'm more concerned with forgetting.

**Comment by nunziotocci** [comment]
I can't reproduce in Postage, or PG****n III for that matter, did he say what version of PostgreSQL?

**Comment by justintocci** [comment]
I'll see him at the next DFW Postgres meetup. I'll have him review and give more detail.

**Comment by justintocci** [comment]
I mentioned this to the original guy and haven't gotten a response. I'm going to close it until we figure out how to do more.
