### ISSUE TITLE
Autocomplete inserts entire word instead of completing word

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#244]
Autocomplete inserts entire word instead of completing word.

Steps to reproduce: 

insert a character in front of the cursor, I used a semicolon.
start typing and get a drop down. 
hit TAB to complete the word.

expected word to be completed, but instead the entire word was inserted after my characters. This leads to duplicate letters. Example attached is for column "lot_qty" got autocompleted to "lotlot_qty".

![screen shot 2017-05-06 at 11 48 27 am](https://cloud.githubusercontent.com/assets/14250339/25774267/f65c8678-3251-11e7-9bb7-abf7fa975698.JPG)

**Comment by crosstocci** [comment]
Fixed in next release.
