### ISSUE TITLE
Autocomplete PL/PGSQL variables

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/postage#247]
When autocompleting variables in a function, the type is included in the completion:

![capture](https://cloud.githubusercontent.com/assets/7560749/25812526/346661c4-33dc-11e7-9bd2-662615dffe85.PNG)

---

![capture2](https://cloud.githubusercontent.com/assets/7560749/25812527/346710d8-33dc-11e7-9960-ed10b8ec3600.PNG)

**Comment by crosstocci** [comment]
Fixed in next release.
