### ISSUE TITLE
Table designer does not handle `serial` columns properly

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/postage#248]
When it tries to drop the table to rename the new one, the sequence prevents it from succeeding.

I looked at the dependents for the table, and sure enough the sequence is in there.
I think we should detect when a sequence depends on the table, and create the column as the proper serial type, then alter the sequence to have the proper value.

**Comment by nunziotocci** [comment]
The reason the sequence is not detected is because the way we detect dependents is by dropping the table and rolling it back, as described in #307.

As a solution, we could either use a dependent query for everything or just for serial columns.

**Comment by justintocci** [comment]
just for serial columns. We tried to detect dependents the other way and it didn't work well.

**Comment by nunziotocci** [comment]
Fixed in e0bceb7. Will be seen in next release.
