### ISSUE TITLE
If you drop and re-create a schema, clicking the triangle shows "there is nothing in this folder"

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#251]
If you drop and re-create a schema, clicking the triangle shows "there is nothing in this folder"

Instead, it should figure out that it was dropped and connect to the new schema with the same name. 

If the schema is gone it should remove it from the object browser or at least say that instead of "there is nothing in this folder".

**Comment by crosstocci** [comment]
Fixed in next release.
