### ISSUE TITLE
Tab suddenly not working in code editor

### ISSUE THREAD

**Issue by Vonatzki** [workflowproducts/postage#255]
I'm using version 3.2.11.

Tab functionality in the code editor gets lost. I noticed that the tab focus now sticks on the editor buttons above it, cycling through each button.

I'm trying to determine what really causes it but as of now, all I can say is I get it whenever there's an autocomplete suggestion pop-up most of the time while working on my SQL code.

I'm using Windows 7 x64 machine.

P.S. My team have been enjoying using your app as our client interface with our postgresql server :+1: , pgAdmin 4 is really a mess right now :(

I keep my app updated with every release.

**Comment by justintocci** [comment]
We're working hard on this. There were actually several autocomplete issues in this version. We plan to get a new release out today that fixes the issue. Thank you Vonatzki for your patience.

**Comment by nunziotocci** [comment]
Fixed, will be seen in next release.
