### ISSUE TITLE
When I attempt to type a subquery I don't get the choice for a SELECT snippet.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#256]
![screen shot 2017-05-11 at 2 08 35 pm](https://cloud.githubusercontent.com/assets/14250339/25967483/f36e61b0-3653-11e7-9caf-36c768371d2d.JPG)

**Comment by nunziotocci** [comment]
Currently, you have to type "SELECT_" for the snippets to popup, is that good enough?
If we make it always do snippets in the completion list, it could get annoying.

**Comment by josephtocci** [comment]
Fixed, will be seen in next release.
