### ISSUE TITLE
Drop down showing up for SPACE and characters that should cause no items to appear in drop down.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#257]
![screen shot 2017-05-11 at 2 31 47 pm](https://cloud.githubusercontent.com/assets/14250339/25968382/deaf0df8-3656-11e7-90d8-5f1499998199.JPG)
![screen shot 2017-05-11 at 2 31 58 pm](https://cloud.githubusercontent.com/assets/14250339/25968386/dfcd60f4-3656-11e7-8919-c37a526d36dc.JPG)

**Comment by justintocci** [comment]
Note that, no items in the drop down are showing a space or an exclamation point as the first character, so none of them should be showing in the drop down.

**Comment by josephtocci** [comment]
Fixed, will be seen in the next release.
