### ISSUE TITLE
Beautify puts commas first on a line, not everyone likes that.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#263]
I used to hate comma first formatting, now I can't deal with it any other way. I think it would be best if we were sensitive to the programmers that don't like comma first formatting. After all, Postgres defaults to comma last formatting for tables, I'm sure there is an argument for consistency there.

Let's add an option in the preferences to cause beautify to format comma first or last.

**Comment by Vonatzki** [comment]
Agreeing on this one. I find comma first formatting a bit jarring. Thanks for bringing this up.

**Comment by crosstocci** [comment]
Fixed in next release, it now defaults to comma first and may be changed in the postage options pane.
