### ISSUE TITLE
Groups SQL

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#264]
When we have a user or a ground, then we have anything that that role is a part of below it;
````
CREATE ROLE joseph
...
GRANT envelope_g TO ...
````
I want to add grants in the other direction, we can put them in a comment if we don't want to run them as soon as we add a group, but it helps to determine who has a group very quickly. Like this:
````
CREATE ROLE envelope_g
...
/*
GRANT envelope_g TO joseph;
*/
````

This would save time either looking through the users to find out everyone who has a group, or running pg_catalog to determine who has a group. 90% of the time you shouldn't have to look at a pg_catalog when you are already running administration software.

**Comment by justintocci** [comment]
Note that, we still have code for the postal inspector in Postage, though there is no button to get to it.

**Comment by josephtocci** [comment]
Fixed, will be seen in the next release.
