### ISSUE TITLE
Javascript error notifications

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#265]
We should overwrite console.error and have it send us a stack trace so we can track it down as soon as it happens. I don't think that it should be active by default for envelope, but I think we should consider it for Postage.

This type of thing for desktop applications usually ask if they want data sent to vendor in the event of a crash, this wouldn't be for a crash it would be for javascript issues. Perhaps a popup asking for permission would be best. We set a cookie with the answer, and it only asks if there is no cookie detected. If the cookie says yes, then we just automatically send the stack trace to us and have a message on the screen saying that a stack trace was sent.

Thoughts?

**Comment by justintocci** [comment]
i like it.

**Comment by nunziotocci** [comment]
I don't think overwriting console.error would work for syntax errors in the browser, but in the electron version this is definitely possible.

**Comment by michaeltocci** [comment]
No need to overwrite anything, just listen on `window.onerror`

[http://mattsnider.com/window-onerror-event/](http://mattsnider.com/window-onerror-event/)

**Comment by crosstocci** [comment]
Added in next release.
