### ISSUE TITLE
Error when running a second instance of Postage

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#267]
Windows Server 2008 R2
Postage 3.2.12

![image](https://cloud.githubusercontent.com/assets/1327493/26405089/1c9858a6-408c-11e7-88c3-45273c55a431.png)

It would be great to handle this more gracefully - either by displaying a message telling the user that Postage is already running, or by causing the existing instance to open a new window which then gets focus.

On clicking OK the login screen appears, but I've no idea if that instance of Postage is now broken in some way.

**Comment by nunziotocci** [comment]
Thanks for this, I'll get it fixed soon.

As a work-around, you can use File > New Window to open another database.





--
Regards,
Annunziato Tocci
Programmer
www.workflowproducts.com
7813 Harwood Road
North Richland Hills, TX 76180
Land 817-503-9545
Mobile 817-733-9591
Skype nunziotocci
