### ISSUE TITLE
"Edit Data" dialog issues

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#268]
Windows Server 2008 R2
Postage 3.2.12

When using the Edit Data dialog it seems like changes to a cell's contents are committed immediately after the cell loses focus.

This means that a user isn't given a chance to revert the changes they've made, or make multiple changes in one transaction (which might be needed to ensure the new values satisfy a constraint, for example). Even leaving the cursor in a cell whose value has been changed and clicking the "Refresh Data" button still commits the change, so the "refreshed" data is identical to what is already displayed.

It would be nice if commits were only done when the user clicked a "Commit" or "Save" button, and until then any edited cells perhaps had a red background. Attempting to refresh the data or close the dialog could warn about uncommitted edits.

But either way I think that committing data from here should require more explicit approval, and some feedback when a commit occurs (e.g. "N rows updated").

Also, sometimes, when a cell's contents are edited and this autocommitting takes place I get an error with no message:
![image](https://cloud.githubusercontent.com/assets/1327493/26406394/0c72b9a4-4090-11e7-9c2a-e0b2e79f6f05.png)
![image](https://cloud.githubusercontent.com/assets/1327493/26406411/17a976a0-4090-11e7-95f7-69cabdbfdd0c.png)

In the console I see this:

```
Object
error_context: ""error_detail: ""error_hint: ""error_notice: ""error_position: ""error_query: ""error_text: ""__proto__: Object
greyspots.js:10835 GS.removeLoader Error: loader not found
GS.removeLoader @ greyspots.js:10835
(anonymous) @ datagrid.js:529
(anonymous) @ greyspots.js:9109
socket.onmessage @ greyspots.js:8694
```
I think this is restricted to tables within the "public" schema. In the database logs, for tables in other schemas which are successfully updated, I see "CREATE TEMP TABLE temp_update..." statements, but not for tables in the public schema.

**Comment by nunziotocci** [comment]
I think the empty error dialog will be fixed with our new datasheet (rolling out soon), but the manual commit is a new idea. @michaeltocci @crosstocci could you look into this?

**Comment by justintocci** [comment]
@stevenwinfield We think we have a full solution. 

Here is what we have right now:

Currently, with the new grid, you can paste multiple values over multiple cells and they are sent at once. This is a valid workaround for the 'two columns at once' edit problem that you're having.

For the next release:
We'll have a 'pencil' icon or similar in the record selector for each record. If you click it, you'll get a popup with all the columns, a cancel button and a save button. Changes will again be sent all at once and solve your 'two columns at once' edit problem there as well.

This should solve all your issues as we understand them. Please let us know soon if we're missing something and we'll try to get it into the next release.

**Comment by crosstocci** [comment]
The new update dialog will be seen in next release.
