### ISSUE TITLE
At end of script, near bottom of viewport, returns cause cursor to exit the viewport.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#279]
It used to keep the cursor in view I think. It's strange for the cursor to leave the viewport while allowing typing to occur.

**Comment by crosstocci** [comment]
@josephtocci the problem is that autocomplete overrides the return function and replaces it with:
```editor.insert('\n');```
This has different functionality than just clicking return.

**Comment by justintocci** [comment]
Is it possible this was overridden when it could have been set up to let a return pass through?

If not, is it possible to detect that the cursor is out of the viewport and scroll it back in?

**Comment by crosstocci** [comment]
It now allows a return to pass through.
Fixed in next release.
