### ISSUE TITLE
Please remove the icons from the menu

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#280]
We're just embarrassing ourselves now with the poor alignment. Also, drop down chevrons are supposed to be on the right hand side of the word. Also, drop down menu's shouldn't even have chevrons. It's all just so wrong it hurts...

![screen shot 2017-05-29 at 3 19 27 pm](https://cloud.githubusercontent.com/assets/14250339/26561227/42b56eb2-4482-11e7-91d4-c879224ed75a.JPG)

**Comment by josephtocci** [comment]
I still say we drop FontAwesome and use SVG. Then we don't have to deal with fontawesome character codes and css. It would be as simple as including an image.

**Comment by crosstocci** [comment]
Fixed in next release.

![123123123123123123123123123123](https://cloud.githubusercontent.com/assets/24857334/26561552/f30ac292-4484-11e7-8e90-9625525f4437.png)

**Comment by justintocci** [comment]
mobile can't do SVG
