### ISSUE TITLE
New Grid is not showing last column(s) if i have to side scroll to it.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#281]
If you have trouble reproducing the error, let me know and I'll give you the exact table.

![screen shot 2017-05-29 at 4 25 21 pm](https://cloud.githubusercontent.com/assets/14250339/26562382/7090f73a-448b-11e7-9a07-a0a0bbf01dd3.JPG)

Note that vertical scrolling causes the column(s) to come back.

**Comment by crosstocci** [comment]
Fixed in next release.
