### ISSUE TITLE
DROP FUNCTION SQl contains "DEFAULT"

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#283]
Postage 3.2.12
Postgres 9.6.2

Creating a function like this:

```
CREATE FUNCTION foo(bar integer DEFAULT 0) 
RETURNS integer AS
$$
    select 1;
$$
LANGUAGE SQL;
```

has a DROP statement generated by Postage like this:
```DROP FUNCTION public.foo(bar integer DEFAULT 0);```

which isn't valid SQL - the DEFAULT 0 part shouldn't be there.

Perhaps you need to use ``pg_get_function_(identity_)arguments``?

Thanks.

**Comment by crosstocci** [comment]
Fixed in next release.
