### ISSUE TITLE
Autocomplete doesn't after a parenthesis

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#292]
SELECT avg( | ) OVER (PARTITION BY depname) 

With the cursor at the pipe above it's pretty obvious I want table and column dropdowns but I get nothing.

**Comment by justintocci** [comment]
Seperate issue but likely related:

If my cursor is at the end of the script (on the last line and character) then autocomplete doesn't pop up.

**Comment by josephtocci** [comment]
Fixed, will be seen in next release.
