### ISSUE TITLE
The VIEW script has an error. CREATE TRIGGER should be commented out.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#293]
I have the following code in my script, but it errors because the trigger doesn't go anywhere when I just add a column.

`CREATE TRIGGER trg_instead_qry_schedule_all_color INSTEAD OF UPDATE ON jps.qry_schedule_all_color FOR EACH ROW EXECUTE PROCEDURE jps.instead_qry_schedule_all_color();`

**Comment by crosstocci** [comment]
Fixed in next release.
