### ISSUE TITLE
Pop tab out to new window button is broken

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#297]
![screen shot 2017-06-02 at 2 22 29 pm](https://cloud.githubusercontent.com/assets/14250339/26741457/0bd76998-479f-11e7-8a58-843b037d04d3.JPG)
![screen shot 2017-06-02 at 2 22 21 pm](https://cloud.githubusercontent.com/assets/14250339/26741459/0d4697c2-479f-11e7-9a6f-98d8485f8823.JPG)

**Comment by crosstocci** [comment]
@justintocci I can't reproduce this issue can you show me where this is happening?

**Comment by justintocci** [comment]
seems ok now.
