### ISSUE TITLE
No data displayed in "edit data" tab

### ISSUE THREAD

**Issue by benhowell** [workflowproducts/postage#298]
Not quite sure of the cause but suspect it has something to do with hyphenated table and/or column and/or constraint names in my schema.

Mostly no data is shown at all [1] but in a couple of strange edge cases the data is shown but the content of the hyphenated column is shown as NaN (in these particular cases, the column types are varchar). [2]

[1]
![none](https://cloud.githubusercontent.com/assets/1784519/26751066/4d49c3dc-4874-11e7-8eaa-c6c1ed2c81c5.png)

[2]
![nan](https://cloud.githubusercontent.com/assets/1784519/26751054/ee01dad6-4873-11e7-9a61-c298c98bce31.png)

**Comment by crosstocci** [comment]
The problem was we were accessing a variable using this format:

```row.example-column```

This would cause problems if you have a space or another special character in your column name like this:

```row.example column```

We now access it like so:

```row['example column']```


Fixed in next release.
