### ISSUE TITLE
Can't delete Windows shortcut off desktop

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#3]
New install of Postage on Win10. 

I can't seem to delete the Windows shortcut off the desktop. I'm not an admin user.

I right click or move to the trash. I expect to get a popup asking for an admin password. Instead I get nothing. No error. The icon is basically stuck in place.

**Comment by nunziotocci** [comment]
This appears to be a windows bug.
I checked all of the file attributes against another program's shortcut and they were exactly the same.

You can still delete the shortcut from a File Explorer window.
