### ISSUE TITLE
Cannot put NULL into a table

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#30]
When using the table editor, I cannot remove a date from a date field. NULL values should be handled better.

![screen shot 2016-10-14 at 10 41 53 am](https://cloud.githubusercontent.com/assets/14278246/19411054/8f542b84-92bf-11e6-9dd1-102f88ca35f9.png)

**Comment by nunziotocci** [comment]
You can type in \N to get a null into a table.
