### ISSUE TITLE
Materialized view definitions don't show

### ISSUE THREAD

**Issue by Tostino** [workflowproducts/postage#300]
When trying to look at the definition of a materialized view, I get the following errors in the definition window:
-- This object's script could not be retrieved...
-- Perhaps this object was dropped and/or recreated?

**Comment by justintocci** [comment]
We've decided to add materialized views to the VIEW list. We'll give it a prefix of MV instead of VW.

If anyone thinks that's a bad plan please let us know soon.

**Comment by crosstocci** [comment]
Fixed in next release.
