### ISSUE TITLE
Save query issue - Windows 10

### ISSUE THREAD

**Issue by Tostino** [workflowproducts/postage#303]
I am having issues saving a query I was working on.  I tried both "save file" and "save as".
The error i'm getting is:
```
There was an error:

..\..\util\util_canonical.c:canonical: read_file: \Users\GoSimple\AppData\Roaming\postage\sql\database03_manufacturer_dev\root\|open\Tab%25204.sql is a bad path. Path does not exist.

Failed to get canonical path: >\Users\GoSimple\AppData\Roaming\postage\sql\database03_manufacturer_dev\root|/open/Tab%25204.sql<
```

**Comment by crosstocci** [comment]
@Tostino I can't replicate the issue on Windows 10.

So far I've tried:
- Labeled and unlabeled buttons
- Windows 10 Electron 3.2.14 on a virtual machine
- Windows 10 Electron 3.2.14 on a dedicated machine
- Installing for all users
- Installing for just one user
- Special characters in the tab name

None of these are causing an error.
Is there something different about your install?

Also when this happens could you please go to "View > Toggle Developer tools" and get us the console 
 errors if there are any. That might have pointed us in the right direction.

We'll keep an eye out for this hopefully someone will have some additional information soon.

**Comment by justintocci** [comment]
We're cleaning up today and since we can't move on this without more info we're going to close it. Please feel free to re-open with more info. Next time this happens, please post your Postage Version, Electron/non-electron, OS, and console errors.
