### ISSUE TITLE
LOGIN and PASSWORD on same line in CREATE ROLE script

### ISSUE THREAD

**Issue by stevenwinfield** [workflowproducts/postage#305]
Postage 3.2.12
Postgres 9.6.2

Show login roles. Click a role -> Get a script like:

```
CREATE ROLE someuser
    LOGIN PASSWORD '*******'
    NOCREATEROLE
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOREPLICATION
    CONNECTION LIMIT -1
    VALID UNTIL 'infinity';
```
It's quite easy to delete the whole "LOGIN PASSWORD ..." line, thereby making a non-login role, whereas  I just wanted to temporarily leave the password blank until the user sets it.
These are separate options, so it think it makes sense to have them on separate lines, as with all the others.

**Comment by justintocci** [comment]
Wants to look like:

CREATE ROLE someuser
    LOGIN 
    PASSWORD '*******'
    NOCREATEROLE
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOREPLICATION
    CONNECTION LIMIT -1
    VALID UNTIL 'infinity';

should be easy!

**Comment by crosstocci** [comment]
Fixed in next release.
