### ISSUE TITLE
Table Design View "generate script" button needs work and testing.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#307]
NEW PLAN!

Instead of trying to figure out the shortest list of objects to be dropped (in an appropriate order) we'll just let PostgreSQL do it. 

First, set up a loop with the DROP TABLE query and a ROLLBACK at the end. 

Each time it errors you add the object that is dependant on it to your script and run it again.

Eventually, the ROLLBACK will be run and you'll will have the shortest list of objects to be dropped and it will be in the appropriate order for an error-free script! 

Next, replace the DROP TABLE in the middle of your script with the RENAME, CREATE TABLE, INSERT and DROP OLD TABLE.

And finally, add all the FUNCTIONS and TRIGGER FUNCTIONS that include the table name in the body of the function.

EASY MONEY! Let's get this done for 3.2.16

**Comment by josephtocci** [comment]
Can't we just use the dependents of the object? Am I missing something?

**Comment by justintocci** [comment]
Well, we've tried that and we still don't have a working version. This seems like a really easy to implement strategy that would be correct all the time. What would be the logic that you would propose?

**Comment by crosstocci** [comment]
On a related note the current version does not support having a rule on the table.

**Comment by crosstocci** [comment]
Ready for testing.

How should we do that?

**Comment by crosstocci** [comment]
Added in next release.
