### ISSUE TITLE
Right-Justify Integers and Decimals in Query Results

### ISSUE THREAD

**Issue by anthonydb** [workflowproducts/postage#31]
For better readability and comparisons of numbers, please right-justify any integers or decimals in the Postage results grid. The current behavior (see screenshot) makes it harder to scan the columns and look for meaning in the results.

![screen shot 2016-10-16 at 5 27 37 pm](https://cloud.githubusercontent.com/assets/273891/19421054/f622b9c8-93c5-11e6-93ff-022173d00a2f.png)

**Comment by anthonydb** [comment]
Here's the `psql` formatting for comparison.

<img width="702" alt="screen shot 2016-10-16 at 5 29 30 pm" src="https://cloud.githubusercontent.com/assets/273891/19421063/2b6d1556-93c6-11e6-8c0f-ce85b71b0e84.png">

**Comment by michaeltocci** [comment]
Thanks for the suggestion!

I've made a list of all the types that should be right-justified:
- int2 / smallint
- int4 / integer
- int8 / bigint
- numeric
- float
- decimal
- real
- double
- money
- oid

I'll be making all of these types right-justified in the Postage results tables and in the datasheet.

**Comment by michaeltocci** [comment]
I've published the changes. They will be released on Saturday.

**Comment by anthonydb** [comment]
FYI, in the newest version of Postage this behavior has reverted to integers being left-justified.
![screen shot 2017-08-10 at 12 00 46 pm](https://user-images.githubusercontent.com/273891/29179794-9f6d2648-7dc3-11e7-91ad-a9f50ecc654d.png)

**Comment by crosstocci** [comment]
Fixed in next release.
