### ISSUE TITLE
Datasheet Selection after update

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#311]
When you copy and paste, then move up or down a column using arrow keys, the whole column gets selected. However, after the update finishes the selection changes from whole field to cursor at the beginning of the column, if I am trying to update four or five columns at once I get something like this:

![screen shot 2017-06-13 at 3 38 52 pm](https://user-images.githubusercontent.com/14278246/27142718-8da250f4-50f1-11e7-9af4-55d39fe111e4.png)

On a related note, NULL should be a placeholder, not a value.

**Comment by crosstocci** [comment]
Fixed in next release.
