### ISSUE TITLE
Large buttons in GUI

### ISSUE THREAD

**Issue by Vonatzki** [workflowproducts/postage#313]
Just an aesthetic qualm of mine. Latest version made the buttons look uncomfortably bigger for my taste; wasting screen real estate. My monitor resolution is 1366 x 768 using Windows 7 x64..

![capture](https://user-images.githubusercontent.com/12231265/27162528-515393f6-51b4-11e7-90f6-ab4853cc63e5.PNG)

**Comment by Vonatzki** [comment]
I just found out there's a CSS editor on the options pane. Will investigate if I can modify the size of the buttons. Hoping that subsequent iterations have an pleasing button size out of the box.

**Comment by justintocci** [comment]
I apologize for the delay. Time zones!

Please go to "Options" > "Postage Options" and click "SQL Toolbar Button Style" to "Unlabeled".

Let us know if that works or if you prefer something else.

**Comment by Vonatzki** [comment]
Actually, I already set my buttons to unlabeled for now.

But I kinda miss the previous iteration where the buttons are labelled but only taking up just a row of space in the toolbar.

I know it's not really a big deal compared to other issues present, so no rush. Take your time and thanks for responding quickly to my queries! :)

**Comment by justintocci** [comment]
no problem. Screen space is one of our pet peeves so we'll get this fixed. 

Cross, please make the buttons a bit smaller. If possible, set your screen size to 2560 x 1440 and make sure that the buttons only fill one row. This should make it look good on the vast majority of desktop screens.

**Comment by justintocci** [comment]
Oh wait, Vonatzki's screen is smaller than that. Make it 1366 x 768 but you may have trouble.

Remove the word "Toggle" from the comment button. If we need to do more let's discuss. 

Maybe we can combine the two save options, Download and Export all into a dropdown.

**Comment by crosstocci** [comment]
Fixed in next release.

- Changed "Toggle Comment" to "Comment"
- Changed "Ace Tips" to "Ace"
- The save buttons are only supposed to be visible on electron
- Changed the padding on the buttons from 6px to 4px

**Comment by Vonatzki** [comment]
Thanks Cross!

**Comment by crosstocci** [comment]
No problem @Vonatzki we're always here to help!
