### ISSUE TITLE
Permissions on columns does not work

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#316]
I ran this SQL:
![screen shot 2017-06-21 at 3 38 09 pm](https://user-images.githubusercontent.com/14278246/27486019-beb797c6-57f4-11e7-9f5b-083fbf833d0a.png)

Then Postage gave me this which is not correct:
![screen shot 2017-06-21 at 3 37 55 pm](https://user-images.githubusercontent.com/14278246/27486020-bece18fc-57f4-11e7-89cd-a4610aceb2fd.png)

**Comment by crosstocci** [comment]
Fixed in next release.
