### ISSUE TITLE
Beautify on a table

### ISSUE THREAD

**Issue by crosstocci** [workflowproducts/postage#318]
![image](https://user-images.githubusercontent.com/24857334/27500742-5f76017c-582f-11e7-96e5-cf1a3d889012.png)

**Comment by crosstocci** [comment]
Fixed in next release.

**Comment by iKlsR** [comment]
@crosstocci The majority of the links over at releases point to these issues, hardly useful for newcomers who want to quickly inspect stuff as these are just the issues, would like to see the corresponding PR that fixed the issue. Could I suggest using [Github's #fixes or #closes syntax](https://help.github.com/articles/closing-issues-using-keywords/) in the future. Thanks.

**Comment by justintocci** [comment]
I've opened a new issue: https://github.com/workflowproducts/postage/issues/340

We'll discuss changing our process there and let you know what we're going to do.
