### ISSUE TITLE
ACE Editor: Quick way to surround highlighted part with parentheses

### ISSUE THREAD

**Issue by Vonatzki** [workflowproducts/postage#320]
In other text editors, when you highlight something then press the "(" (open parenthesis) it surrounds the highlighted part in parentheses.

Are there plans to incorporate this feature in the editor pane of Postage?

Thanks!

**Comment by crosstocci** [comment]
@Vonatzki, We are not planning on incorporating this feature into postage.

That being said you may try opening an issue in the [ajaxorg/ace](https://github.com/ajaxorg/ace) Repository.

The fastest way that we've found to do this right now is: 
* Cut
* Type "("
* Paste
* Type ")"

Of course if that doesn't work for you then patches are welcome!

**Comment by Vonatzki** [comment]
Noted! I guess the good ol' cut and paste would suffice.
