### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by crosstocci** [workflowproducts/postage#325]
If a statement has white-space before it the statement loses its syntax highlighting.

**Comment by justintocci** [comment]
Yes the syntax highlighting turns off if you indent the query.

This is especially problematic in FUNCTIONs where you're typically going to indent SQL statements.

**Comment by crosstocci** [comment]
This is an issue with the ace pgSQL mode.

I have opened an issue in the ace repository here: ajaxorg/ace/issues/3360
