### ISSUE TITLE
on error in script run, no line indicator

### ISSUE THREAD

**Issue by tkadado** [workflowproducts/postage#329]
when encountering error without line number from postgres, postage doesn't locate the line number

**Comment by justintocci** [comment]
Say you have ten queries. One of the queries is a one-liner (say it's a GRANT statement). If there is an error in a multi-line query, the editor sends the cursor to the line and marks it with a big red "X", but if the error is in the one-line query, it does nothing. It doesn't scroll to the error, or mark it.

please fix.

**Comment by josephtocci** [comment]
Fixed, will be seen in next release.
