### ISSUE TITLE
Arrow up/down

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#33]
Sometimes, for no reason, postage prevents me from arrowing up or down in the editor. This does not happen on a postage server, I have only noticed it on the electron version.

**Comment by josephtocci** [comment]
Update: Also when this starts happening, I can't tab anymore, it changes focus to one of the buttons. I think this is a focus problem.

**Comment by michaeltocci** [comment]
Could you get an exact set of steps that I can follow to replicate this issue?

Also, please attach some SQL that the problem occurs inside.

My guess is that this is a problem with the autocomplete code.

**Comment by josephtocci** [comment]
I have been unable to replicate on command, but as soon as it starts I have to restart postage.

**Comment by josephtocci** [comment]
Unable to replicate in a long time, and I am told Michael made a change in an effort to fix it a while ago. I am closing this, I will re-open if it happens again. I expect Michael has fixed it.
