### ISSUE TITLE
need to use postage as file editor

### ISSUE THREAD

**Issue by tkadado** [workflowproducts/postage#330]
I'm having a difficult time jumping from my editor to postage.
I need to be able to use postage as file editor:  open, remember file location and history, remember where the files are saved, and other basic features of file editor

**Comment by nunziotocci** [comment]
I had implemented this before, but I went to check it and it wasn't working properly.

I have fixed it and here is how to use it:
- To open a file, click Tab > Open File...
- To save, click the floppy icon
- To save under a different name, click the floppy/pencil icon
