### ISSUE TITLE
Workflowproducts.com postage screen shots should be clickable

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#334]
bdcravens 51 minutes ago | unvote [-]

Screenshots on https://www.workflowproducts.com/postage.html should be clickable thumbnails for larger preview. Otherwise those are too small to see much detail

https://news.ycombinator.com/item?id=14884183#14884501

**Comment by bdcravens** [comment]
Obligatory +1 :-)

**Comment by NewbiZ** [comment]
That really is necessary. It's tough to convince people to use a GUI application without real screenshots

**Comment by michaeltocci** [comment]
Fixed. Some may still have the old page cached.

For those curious, I used [Colorbox.js](http://www.jacklmoore.com/colorbox/), it's a nice little MIT lightbox. I would've preferred something without jQuery, but it has the feature set that I wanted.
