### ISSUE TITLE
It's time we promoted Postage

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#337]
We've got some great workflows so here is what I'd like to see. Each item wants to be a very short video explaining a cool workflow in Postage.

1) Autocomplete 

2) Refactoring workflow. We have the schema dump functionality which makes it easy to refactor when you need to change a column's name or data type. We need a quick video explaining the process.

3) ACE rocks! Non-contiguous select, typing and find/replace. These are extremely useful, time-saving features that few editors have so showing them off is worthwhile.

4) Table editor. We let people generate a script to alter tables and the script includes all the affected objects and few that are not affected. It's a great workflow but not obvious. Promoting it would get people using Postage for those major surgery situations. That makes PostgreSQL more accessible and easier to use than other databases without this workflow.

5) PostgreSQL drops formatting from VIEWs so we have the Beautify button. It makes it easy to read your complex SQL despite PostgreSQL.

6)  Cell-based copy/paste. We have all the features of Microsoft Access's datasheet but it isn't obvious that we're that full-featured. A short video would point out all the cool workflows that we support around copy/paste functionality.

**Comment by josephtocci** [comment]
I Found a community PostgreSQL GUI list:
https://wiki.postgresql.org/wiki/Community_Guide_to_PostgreSQL_GUI_Tools

Probably just need to ask on IRC to add Postage to the list, since they have had a lot of spam activity on the wiki we need someone who already has editing privileges.

**Comment by justintocci** [comment]
We submitted there before but didn't get on the list. The list doesn't have pga4(as of Aug 11, 2017). My impression is that it is not being maintained and that's why our request went unanswered.

**Comment by nunziotocci** [comment]
Sorry, closed wrong issue

**Comment by nunziotocci** [comment]
I think we can close this one now.
