### ISSUE TITLE
installing on D: breaks postage

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#339]
via hacker news:

makkesk8 16 hours ago [-]Looks great! Decided to install it and test it only to be met with a blank screen, the dev console contains no errors as well. Anyone else having this issue? (windows 10, latest release)

watsocd 10 hours ago [-]I got the same. Just a blank screen. When I clicked on the menu selections to edit the configuration files, it just opened another empty window.Windows 10 latest.

I'm trying but I can't reproduce the error.Microsoft Windows 10 Pro Version	10.0.14393 Build 14393(latest)uninstalled Postage removed the following folders: C:\Users\jtocci\.postage C:\Users\jtocci\AppData\Roaming\Postage C:\Program Files (x86)\Workflow ProductsDownloaded Postage.Windows.3.2.16.zip tried to install by double-click. nothing happened. (known Electron issue) right click to run as administrator install for all users, default locationPostage popped right up. Any ideas how I can get the error you're getting?

I did not install on C:. I installed on D:I uninstalled and reinstalled as Administrator C: and it works now.reply |   |   | watsocd 55 minutes ago [-]I did not install on C:. I installed on D:I uninstalled and reinstalled as Administrator C: and it works now.

**Comment by nunziotocci** [comment]
Fixed, will be seen in next release.
