### ISSUE TITLE
Start using pull requests to address issues

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#340]
iKlsR has posted the following comment [here:](https://github.com/workflowproducts/postage/issues/318#issuecomment-318937437)

@crosstocci The majority of the links over at releases point to these, hardly useful for newcomers who want to quickly inspect stuff as these are just the issues, would like to see the corresponding PR that fixed the issue. Could I suggest using Github's #fixes or #closes syntax in the future. Thanks.

Edit - Looks like the majority of work is done directly from and pushed to master as opposed to feature prs..

--
How hard would it be to switch our process to start using pull requests instead of pushing to master?

**Comment by crosstocci** [comment]
I will begin using the #closes syntax as suggested, that should be make it easier to find the associated code.
