### ISSUE TITLE
Walkthrough of the installation process on ubuntu and/or centos

### ISSUE THREAD

**Issue by parthgandhi7** [workflowproducts/postage#341]
First of all, I want you to know that i have a postgresql hosted on server and i want to access it from local system. So, is this possible with postage? 

I tried installing postage on my local ubuntu system through the rpm installer which resulted in an error saying : 
```
error: Failed dependencies:
	/bin/sh is needed by Postage-3.2.16-1.i386
	postgresql-libs is needed by Postage-3.2.16-1.i386
```

which i think means that it needs postgresql installed my local machine which obviously is not there.

So i tried installing on the remote server where postgresql is hosted, it succeeded saying:
```
Preparing...                          ################################# [100%]
Updating / installing...
   1:Postage-3.2.16-1                 ################################# [100%]
```
But i am not sure what is to be done next. Can you please guide me further? Thanks.

FYI:
On the server (where postgres is installed), os is "CentOS Linux release 7.3.1611"
On the local machine, os is "Ubuntu 16.04.2 LTS".

**Comment by nunziotocci** [comment]
@parthgandhi7 You are trying to install on Ubuntu with a RedHat package.

To Install on Ubuntu, download the .deb package and run:
```
sudo apt install ./Postage-whatever.deb
```

To Install on RHEL/CentOS, download the .rpm package and run:
```
yum install ./Postage-whatever.rpm
```

I will add this to the README.

**Comment by nunziotocci** [comment]
Let me know if there are any more problems.

**Comment by parthgandhi7** [comment]
Ok, thanks for the help. Just one more thing , the downloads of the deb package seems to be broken. Whenever i try to download the deb package, it always fails at some point. I have tried downloading it 5-6 times. Can you please verify and tell me its not an issue from your side?

**Comment by nunziotocci** [comment]
It seems like that would be your internet connection, right now it takes me a few seconds to download each.
GitHub is hosting the files so any issue with that should be directed at them (I think).

**Comment by sunnyrjuneja** [comment]
Would ya'll consider maintaining a PPA instead?

**Comment by justintocci** [comment]
Nunzio did a little research. He feels it would add to the release time. I'm sorry, we just can't afford it at this time.

**Comment by sunnyrjuneja** [comment]
no worries!

**Comment by parthgandhi7** [comment]
Finally, i managed to download and install [Postage_3.2.16_i386.deb](https://github.com/workflowproducts/postage/releases/download/eV3.2.16/Postage_3.2.16_i386.deb) on my local system (with Ubuntu 16.04.2 LTS). 

Now, when i search for postage in my searchbar and click on 'postage' , the postage icon appears for a while in the sidebar (as if it is trying to open) and then vanishes. I tried this 3-4 times but it is not working. Can you please help me out @nunziotocci . 

Thanks

**Comment by nunziotocci** [comment]
@parthgandhi7 It sounds like Electron is having a problem. Could you open Terminal and type this:
```
/opt/Postage/postage
```
And paste the output?

**Comment by parthgandhi7** [comment]
This is the output:
`/opt/Postage/postage: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory`

**Comment by nunziotocci** [comment]
It sounds like you installed Postage without resolving it's dependencies (e.g. with `dpkg`).
At this point, you can either:
- manually install all of the dependencies
- uninstall Postage and reinstall using `apt` to get all dependencies.

**Comment by parthgandhi7** [comment]
yeah i did install by clicking on the deb file i.e. equivalent to dpkg. I tried uninstalling and reinstalling postage with `sudo apt install ./Postage_3.2.16_i386.deb -f`. The result remains the same.

**Comment by parthgandhi7** [comment]
FYI: i removed postage with `sudo apt remove postage:i386` followed by `sudo apt autoremove` and then reinstalled it with the above mentioned command.

**Comment by nunziotocci** [comment]
From what I can tell, `-f` is for fixing an installed (but broken) package, try removing Postage and installing it with:
`sudo apt install ./Postage_3.2.16_i386.deb`

**Comment by parthgandhi7** [comment]
I doubted that -f would have created problem and i am right. tried reinstalling with ur command but the result remains the same.

**Comment by nunziotocci** [comment]
Ok, let's try installing dependencies manually:
```
sudo apt install libxss1 libpq5 gconf2 gconf-service libnotify4 libappindicator1 libxtst6 libnss3
```

**Comment by parthgandhi7** [comment]
After installing, on `/opt/Postage/postage` it says `bash: /opt/Postage/postage: No such file or directory`

**Comment by parthgandhi7** [comment]
same result
`/opt/Postage/postage: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory`

**Comment by nunziotocci** [comment]
It sounds like you uninstalled Postage earlier and didn't reinstall. What does `sudo apt install ./Postage_3.2.16_i386.deb` say?

**Comment by parthgandhi7** [comment]
yeah i removed that comment reinstalled postage but same result again.

**Comment by nunziotocci** [comment]
Ok, I think I've got it. Are you on a 32-bit or 64-bit OS? [This issue](https://github.com/ethereum/mist/issues/2469) seems very similar.

**Comment by parthgandhi7** [comment]
I am on 64 bit os.

**Comment by parthgandhi7** [comment]
So, i think i should be using [this](https://github.com/workflowproducts/postage/releases/download/eV3.2.16/Postage_3.2.16_amd64.deb) right?

**Comment by nunziotocci** [comment]
Ok, install the "amd64" package and that should work. "i386" is for 32-bit OSes.

**Comment by parthgandhi7** [comment]
ok i would get back to you after that.

**Comment by parthgandhi7** [comment]
Thanks, that worked. Thanks for your time. I would get back to you if i get some other issue.

**Comment by parthgandhi7** [comment]
@nunziotocci One small query, can i connect to multiple instances of postgres from postage? I actually have a dev postgres on one server and a prod postgres on other server. So, i wanted to know if i can connect to both of them simultaneousy and can switch between them.

**Comment by justintocci** [comment]
Yes! Postage menu > File > New Window will give you a new login screen and you can have as many connections as you like.

**Comment by parthgandhi7** [comment]
ok thanks @justintocci.
