### ISSUE TITLE
Minor packaging issues

### ISSUE THREAD

**Issue by basvandijk** [workflowproducts/postage#343]
Inspired by the article about postage on Hacker News I created a [PR for NixOS](https://github.com/NixOS/nixpkgs/pull/27796) providing the postage package and a NixOS module which, when enabled, adds a systemd service which starts a fully configured postage.

In the process of packaging postage I discovered three minor problems in the configure and make scripts:

* The root configure script doesn't pass its arguments to the postage configure script. This causes problems because the [Nix package](https://github.com/LumiGuide/nixpkgs/blob/1376b98e7287bb18e613f9c877b8888aeff93db3/pkgs/applications/misc/postage/default.nix) needs to pass the prefix argument.

* The postage configure script only accepts the `-p` option. Normally unix configure scripts also accept the `--prefix` option which is what Nix is using by default. It would be nice if `--prefix` was supported as well.

* The postage Makefile assumes that the directories `@prefix@/sbin` and `@prefix@/@MANDIR@/man1` exists. On most Linux distributions this is the case but since Nix stores packages in their own unique and isolated directory these directories don't exist. It would be nice if the install target created these directories as well.

I currently work around these issues by [patching](https://github.com/LumiGuide/nixpkgs/blob/1376b98e7287bb18e613f9c877b8888aeff93db3/pkgs/applications/misc/postage/configure-make.patch) the scripts but it would be nice if it worked out of the box.

I also discovered that the man page mentions the `local-only` config option. However when I specify that option in the config file postage crashed with: "Unknown config section/name:  local-only". I tried both `local-only` and `local_only`. It would be nice to have this option. It would be even nicer if I could specify the listen IP address myself.

**Comment by nunziotocci** [comment]
> Inspired by the article about postage on Hacker News I created a PR for NixOS providing the postage package and a NixOS module which, when enabled, adds a systemd service which starts a fully configured postage.

Wow, thanks for this!

> - The root configure script doesn't pass its arguments to the postage configure script. This causes problems because the Nix package needs to pass the prefix argument.
> - The postage configure script only accepts the -p option. Normally unix configure scripts also accept the --prefix option which is what Nix is using by default. It would be nice if --prefix was supported as well.
> - The postage Makefile assumes that the directories @prefix@/sbin and @prefix@/@MANDIR@/man1 exists. On most Linux distributions this is the case but since Nix stores packages in their own unique and isolated directory these directories don't exist. It would be nice if the install target created these directories as well.

I will get right on these.

> I also discovered that the man page mentions the local-only config option. However when I specify that option in the config file postage crashed with: "Unknown config section/name: local-only". I tried both local-only and local_only. It would be nice to have this option. It would be even nicer if I could specify the listen IP address myself.

My bad, the man page isn't supposed to say you can specify that in the config file. That option was only added for the Electron version so that nobody else can connect to your running Postage.

**Comment by basvandijk** [comment]
Thanks for the fixes!

BTW I see that the OS X build of my PR is [failing](https://travis-ci.org/NixOS/nixpkgs/jobs/259368620) because of an openssl issue. Any idea why that is happening? It might be a Nix issue though. Since I also have a Mac I will run a build myself this afternoon.

**Comment by nunziotocci** [comment]
Ah, I see why it's failing.
On macOS, we recommend people install brew openssl, and we statically link it. But, it looks like NixOS doesn't enable the static libraries when compiling openssl.

I'll have to use the rpath method of ensuring the proper ssl library is used.

**Comment by basvandijk** [comment]
Yes, nixpkgs uses dynamic libraries. 

It would be great if you can use the rpath method!

**Comment by basvandijk** [comment]
Cool, I'll try your rpath fix this evening.
