### ISSUE TITLE
Feature request: button to AutoFit columns

### ISSUE THREAD

**Issue by basvandijk** [workflowproducts/postage#345]
I must say that postage is a great tool. You can see that a lot of love and hard work has gone into it. A major improvement upon pgadmin3 (I never tried pgadmin4 because I couldn't get it to work on NixOS).

What would be a nice-to-have is an AutoFit columns feature in the "Edit Data" tab (like in MS Excel). The way I envision it to work is that there's a button on the toolbar (optionally with a key-binding) just above the data grid that when clicked has the effect of adjusting all the columns to the minimum width where all the data in them are visible in the current view. In other words, clicking the button has the same effect as when all the column edges are manually double clicked.

**Comment by michaeltocci** [comment]
Thanks for the compliments!

I've added an AutoFit button to the "Edit Data" tab and the query results data tables. These changes will be available in the next release.

Until then, you can select multiple columns, right click on the header and then click "Fit To Content".

**Comment by basvandijk** [comment]
Wow, half an hour between feature request and implementation. Impressive.

**Comment by Vonatzki** [comment]
@basvandijk  yes they are indeed impressive. My analytics team already uses this tool for a few months now and it helped us a lot.
