### ISSUE TITLE
Quick edit test with postage, someone updated this record before you

### ISSUE THREAD

**Issue by therealmarv** [workflowproducts/postage#347]
Hi,

I just wanted to test out postage today and ran a very quick test. Logged in as db admin (with full rights) on my local Postgres (9.4.4.1) and wanted to change very simple values in my tables.

No matter if I change text or boolean values I always get this error message. What does this even mean?

Someone updated this record before you. (this is the full error message)

![image](https://user-images.githubusercontent.com/1050582/28824996-d4500f5c-76c4-11e7-96ae-77d2c2c7a07b.png)

**Comment by nunziotocci** [comment]
@therealmarv Is the table you updated being updated live, or is this just a test table?

When you try and update a table, we take a hash of the record(s) and compare it to the database, if it matches we update, if not, we error as you've seen.

**Comment by therealmarv** [comment]
It's just a test table on my localhost. I opened it exclusively in postage. I've no problems with editing in pgadmin but with postage on first test.

**Comment by justintocci** [comment]
This sounds like maybe you have more than one primary key or maybe something else we've overlooked. Could we get a look at your table? No data, just the CREATE statement and any TRIGGERs or other code.

**Comment by justintocci** [comment]
Also, there is another mode for editing called multi-update. Try that by clicking the button with the same name. What it does is it let's you change more than one field of data at a time without saving in between each field.

Let us know please.

**Comment by nunziotocci** [comment]
@therealmarv I apologize for not figuring this out sooner.
The problem was a discrepancy between how the JS and the C hashed a record (this is how we check if a record has changed). The problem has been rectified and a test added.
