### ISSUE TITLE
How to drop databases?

### ISSUE THREAD

**Issue by basvandijk** [workflowproducts/postage#349]
In pgadmin3 I can drop a database by right clicking on the database and clicking on "Delete/Drop". Is it possible to drop a database from within the postage interface?

I did try running the following SQL from the `postgres` database:

```sql
DROP DATABASE mydatabase;
```

but that resulted in:

```
ERROR:  DROP DATABASE cannot run inside a transaction block
```

Maybe I missed a button somewhere...

**Comment by nunziotocci** [comment]
When you run a query in Postage, it runs everything in a transaction block (well, [almost...](https://github.com/workflowproducts/postage/issues/302)).

So, to run a query that requires being outside a transaction block, you need to run it thusly:
```sql
COMMIT;
DROP DATABASE mydatabase;
BEGIN;
```

We should add an option to disable the transaction block for the current tab.

**Comment by basvandijk** [comment]
Oh that's a smart trick, thanks!

A dedicated button would be nice but since dropping databases is not a very common operation I don't think it's that important.
