### ISSUE TITLE
Will there be linux support?

### ISSUE THREAD

**Issue by ramses-lopez** [workflowproducts/postage#352]
Do you have linux support planned somewhere down the road? 
Or is there anyway I could just grab the code and compile it to use it in linux?

Great work, btw!

**Comment by nunziotocci** [comment]
I'm not sure I understand, we fully support Linux. We have Ubuntu (.deb) and Fedora (.rpm) releases [here](https://github.com/workflowproducts/postage/releases). If you use a different distro/package manager, you can [compile from source](https://github.com/workflowproducts/postage/blob/master/INSTALL_WEB_SERVER_MODE.md).

**Comment by vannitotaro** [comment]
@nunziotocci I think it was a legitimate question, because Linux is not mentioned on the project homepage https://www.workflowproducts.com/postage.html

**Comment by nunziotocci** [comment]
Oh, that didn't occur to me. I'll fix that now.

**Comment by ramses-lopez** [comment]
I got here following the project homepage that @vannitotaro mentioned.
I did not check the releases page, sorry about that.

Thank you both!

**Comment by nunziotocci** [comment]
I've added screenshot for Linux Postage.
