### ISSUE TITLE
Setting the "super_only" parameter to false

### ISSUE THREAD

**Issue by brunorsini** [workflowproducts/postage#354]
Can't connect to my database because of this. Can't find the documentation online anywhere so don't know how to do it : /

**Comment by justintocci** [comment]
So you need to change this:

# super_only = true

To this:

super_only = false

On a related note, we've made a change to Postage, future versions will have super_only = false
as the default for fresh installs.

**Comment by nunziotocci** [comment]
In the electron version:
Go to File > Edit postage.conf
You can change the parameters and look at the docs from there

In the server version:
Edit /usr/local/etc/postage/postage.conf
And you can 'man postage'

**Comment by brunorsini** [comment]
Pardon my ignorance but I installed the .dmg for MacOS. Where is the config
file on the mac?

**Comment by brunorsini** [comment]
Found it. Thanks a bunch!

**Comment by nunziotocci** [comment]
Pardon me, the DMG *is* the electron version (so is any desktop version you'll find).
So you just have too open postage and go to File > Edit postage.conf
