### ISSUE TITLE
when you create a new tab, it's created at the left instead of the right

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#357]
On the topic of stuff that feels weird, when you create a new tab, it's created at the very left of the tab bar, rather then on the right-hand side (like every application I've ever used that has tabs does). Again, it's not a problem, it's just off-putting.

Let's fix this please

**Comment by crosstocci** [comment]
This has already been implemented.

**Comment by josephtocci** [comment]
It is worth mentioning, that the current version does not have this because it was half done. The current branch has it and it will be seen in the next release.
