### ISSUE TITLE
Clarify Login Screen Connections Options

### ISSUE THREAD

**Issue by anthonydb** [workflowproducts/postage#36]
Thank you for the continual improvements to Postage!

As a user, I'm not clear on what the "test," "ip example," "host example," and "localhost@5432" options are intended to do. Selecting any of them doesn't readily change the inputs or offer user feedback.

**Comment by josephtocci** [comment]
Anthony, those are names for different connection strings that you can use. Edit the file-connections file to change those to your databases.

**Comment by anthonydb** [comment]
Thanks. I guess the thing is that when I click on those names (including one I added), the values don't populate the form fields.

**Comment by justintocci** [comment]
I see what you're saying. Forgive us, it can be hard to use new eyes to look at something we've been looking at for a long time. 

I'm looking at the login page now. Lets create a new section in between "connections" and "credentials". Call it "Or enter a one time connection" and put the host, port, etc, fields in there. That should make it clear that the "one time" fields are not saved.

Next I think it would be good to put something in the connections section that points to the Postage > File > "Edit postage-connections.conf" menu item. 

Perhaps we could try something like the attached photo:
![screen shot 2016-11-02 at 9 24 40 pm](https://cloud.githubusercontent.com/assets/14250339/19954197/3544cf84-a144-11e6-98ca-8fdf36ea8e2d.JPG)

All feedback welcome....

**Comment by anthonydb** [comment]
OK, here's what threw me. I was expecting the Host, etc. values to get filled in when I chose one of the items in the list. It went over my head that by highlighting it I was selecting it.

Yes, maybe some clarifying wording would help dumb users like me! And yes, a link to edit the connections file from the login would be good.

**Comment by justintocci** [comment]
That helps a lot Anthony. I'm thinking we're moving in the right direction. At the top under "Login", let's replace "connections" with "Choose a server". 

Regarding adding a link to edit connections, let's make "You can add new connections to this list from the 'File' menu" a url that goes straight to the connection list.

**Comment by josephtocci** [comment]
I used Michael's account and made the changes. The link is instead a button that says "Edit postage-connections.conf". Nunzio wants to make the button open the window a little differently before it is closed. It will be seen in the next release.
