### ISSUE TITLE
if you move the focus away from the text box, the shortcuts stop working

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#361]
Basically, if you move the focus away from the text box, the shortcuts stop working.

Internally, I'd assume that this is because the shortcuts are routed through the editor window, rather then through the application overall.

If we can move the shortcut detection to the window without major surgery let's do so please.

**Comment by crosstocci** [comment]
Which shortcuts? I've been testing them and they work fine even when i'm not focused into the editor.

**Comment by justintocci** [comment]
Ok, let's make it so that if you click in the results window you don't lose focus.

Also, if you click a button, make it so you don't lose focus. This should help a lot.
