### ISSUE TITLE
Graph view improvements

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#363]
> graph view default to zoom-to-fit, at least when it's opened for the first time.
> Additionally, the graph seems to be built vertically. This is also kind of sub-optimal, since modern screens are far wider then they are tall. It'd probably let you view it much more easily if it were structured horizontally.

The above is some feedback we got. I'm happy to give a little time for the default zoom. 

I'm not sure I want to go to a wider view exclusively. Anyone have any ideas? Maybe a toggle button? Before we mess with it I'd like to know if there are any strong feelings out there.

**Comment by nunziotocci** [comment]
I added a setting for horizontal/vertical explain graphs (defaults to horizontal).

Will be seen in next release.
