### ISSUE TITLE
Foreign Key gets PK logo

### ISSUE THREAD

**Issue by clomdd** [workflowproducts/postage#366]
Hi,

On the left navigation pane when expanding "Keys" for a table it is showing two PK constraints. When I look into the table definition you can see that one of these is actually a foreign key.

Thanks,
Chloe

**Comment by clomdd** [comment]
As a follow on, the SQL displayed on the right hand side is also for a primary key, though it isn't what appears in the SQL for the whole table.

**Comment by josephtocci** [comment]
Fixed, will be seen in next release.
