### ISSUE TITLE
pgpass usage

### ISSUE THREAD

**Issue by thoastbrot** [workflowproducts/postage#367]
Hi,

I have a few servers in my .pgpass file (added by pgadmin3 mainly), but when I start postage and choose a server, I still need to provide a login. Ignoring the empty field, I'm getting an error (about the empty password). I tried using the server name (as usual), the IP (because this is used in the postage connection config) and the display name. None of them seem to work, but there's no documentation apart from the link to the official docs explaining the syntax. I haven't found anything besides the bug report that postage should support it.

What should it look like after adding a well-formed line into pgpass and reload postage?

I'd expect the password field to be grayed out/filled with stars or similar...

**Comment by nunziotocci** [comment]
On the login screen, we don't know which connections have a matching pgpass entry, so we don't change anything visually.
Also, the connection parameters have to match the pgpass entry *exactly* for libpq to pick it up. Is it possible you have a typo in the pgpass?

**Comment by justintocci** [comment]
He probably does not have a typo in pgpass if he can log in via pga3. 

I'll look into this shortly and get back to you.

**Comment by justintocci** [comment]
Ok, here is my (lightly edited) .pgpass (from clicking on the button in Postage):

`fsl.domain_name.com:5434:postgres_database_name:postgres_username:full_password`

My postage-connections file (again from clicking the button in Postage):

`FSL: host=fsl.domain_name.com port=5434 dbname=postgres_database_name user=postgres_username`

Once these are set up and I've reloaded Postage, I click on the FSL button and fill in my user name, then click the log in button (leave the password field blank). Postage should log right in. If not, please let us know your setup and get us as much detail as you can about your setup, versions and config files (but edit the password and domain/IP please)

Some notes:
The user name only needs to be filled in the first time. There is a cookie that will remember it for, if I recall correctly, a month.

In the past I've gotten burned by putting tabs in these config files but that hasn't been a problem in a while for me. I just know it was once so you may consider removing all tabs.

Note that unicode characters may also be an issue.

**Comment by justintocci** [comment]
Note that postage-connections file will ignore the user name, I only included it as an example. If it isn't correct it may error.

**Comment by thoastbrot** [comment]
Sorry for the wait. Installed fresh postage 3.2.17.

Doing the same as you did (clicking on the "pg1" entry, entering "postgres" as username, then click "login":

> There was an error:
>
> "FATAL
> ../db_framework_pq/db_framework.c:escape_conninfo_value: escape_conninfo_value: strlen = 0
> Connect failed: fe_sendauth: no password supplied
> "

pgpass line:
`10.4.11.123:5432:*:postgres:verysecret`

connections file:
`pg1:    hostaddr=10.4.11.123 port=5432 dbname=postgres`

**Comment by justintocci** [comment]
Aha! Host works but hostaddr does not! We've reproduced the error so the fix should be posted soon. Thank you for tracking this down for us.

**Comment by nunziotocci** [comment]
Unfortunately, it looks like we can't do anything to fix this in Postage:

> Note that authentication is likely to fail if host is not the name of the server at network address hostaddr. **Also, note that host rather than hostaddr is used to identify the connection in ~/.pgpass**
> 
> [Source](https://www.postgresql.org/docs/9.4/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS)

I'll emit a warning stating this on the config editor when you have `hostaddr` in it.

**Comment by justintocci** [comment]
Ok, so here is how I was able to work around it for now:
 
.pgpass:

`fsl.com:5434:postgres_database_name:postgres_username:full_password`

postage-connections.conf:

`FSL: host=fsl.com hostaddr=10.0.0.1 port=5434 dbname=postgres_database_name`

This worked for me. Please try it and let us know what happens.

**Comment by justintocci** [comment]
This is all so baffling because I could swear I used an ip address in a .pgpass before but even the documentation insists it's hostname or localhost.

https://www.postgresql.org/docs/current/static/libpq-pgpass.html

**Comment by thoastbrot** [comment]
I actually wanted to use a hostname instead, but found that hostaddr wants an IP (can't resolve hostname for some reason) and I didn't have a strong problem with that... thanks, will switch to host tomorrow.  TIL
