### ISSUE TITLE
Null value in datasheet

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#368]
1.
In the datasheet, NULL should be \N because that's what you type in in order to set NULL. Or we need it to be the other way around where you type NULL to get the field to say NULL.

2.
NULL should not be a text value in the input, it should be a placeholder. My cursor should not be able to select NULL because it's not a value.

![screen shot 2017-08-09 at 12 52 20 pm](https://user-images.githubusercontent.com/14278246/29174206-31f14d28-7dab-11e7-9b3f-7dd998dfe2a0.png)

**Comment by justintocci** [comment]
> My cursor should not be able to select NULL because it's not a value.

I don't understand this. We need to be able to select arbitrary columns for copy/paste.

**Comment by josephtocci** [comment]
I mean inside the field, the field can be selected, but not the text inside the input. On github, it says "Leave a Comment" as a placeholder, once you start typing that placeholder disappears.

**Comment by justintocci** [comment]
Oh, yes, you are correct. If the cursor ends up in the field the null should not be in the way. But we need not do something special for null. We could accomplish this by just having the field work correctly. When you click in a field and the field gets the focus, what is already in the field should be selected. This way the first letter you type overwrites the field.

**Comment by crosstocci** [comment]
We have decided to implement a placeholder for "NULL" instead of actually having the text in the cell.

**Comment by crosstocci** [comment]
Fixed in c48f9d4.
