### ISSUE TITLE
Postage won't open on Mac with "allow apps downloaded from Mac App Store and identified developers" checked

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#37]

**Comment by justintocci** [comment]
I download postage.

open dmg 

drag Postage to Applications folder.

Click on existing shortcut in dock. 

* warning, "downloaded blah, blah."

go to system prefs>Security & Privacy >  click the "open anyway" button.

no dice.

Workaround: find Postage in Application folder > right click > click open

If we can't fix this, and I suspect we can't, then I think I want some kind of warning on the DMG background. 

Please let me approve it before you do it. I want to make sure it will make sense to most people.

**Comment by nunziotocci** [comment]
How does this look for when the user opens a dmg?

![untitled](https://cloud.githubusercontent.com/assets/7560749/20154039/3094832a-a68b-11e6-951c-10fd87ee37d9.png)

**Comment by josephtocci** [comment]
I think it would be better to leave off the screen shot and just describe the issue. Something like:

If you have trouble opening Postage for the first time, navigate to the application folder, right click Postage and choose "Open".

**Comment by nunziotocci** [comment]
How does this look?

![untitled](https://cloud.githubusercontent.com/assets/7560749/20184789/8b670abc-a72f-11e6-894b-e615641ec201.png)

**Comment by nunziotocci** [comment]
> You have a “First,” but no “Second,”

How about this?

![untitled](https://cloud.githubusercontent.com/assets/7560749/20185570/2e065546-a732-11e6-9121-055dbe0eded2.png)

**Comment by jentocci** [comment]
Looks good.

Regards,
Jen Tocci, President
Workflow Products LLC
Call, Text, FaceTime:
(817)899-7232
