### ISSUE TITLE
Autocomplete showing too many columns

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#371]
In this example I think maybe the autocomplete search is finding "raccount" inside of "raccount_poc" and showing those columns as well. It still shows the correct columns just also some from the line table.

![screen shot 2017-08-11 at 1 08 56 pm](https://user-images.githubusercontent.com/14278246/29227381-3f8b4f6a-7e9b-11e7-861c-5ff543b9f8da.png)

**Comment by crosstocci** [comment]
@josephtocci fixed this and forgot to close it.
Will be seen in next release.
