### ISSUE TITLE
Autocomplete is broken. Not showing functions, not showing correct schema.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#374]
In the first case, we're not getting any objects. Something about SELECT is not working correctly.

![screen shot 2017-08-14 at 4 36 42 pm](https://user-images.githubusercontent.com/14250339/29293000-f55e575e-810e-11e7-9105-af123c7df2c2.JPG)

In the second case, I move to the FROM clause and I do get a drop down, but it isn't including tables or functions from the ddl schema, and on top of that, it is including tables from the usr schema, which ddl. should exclude.

![screen shot 2017-08-14 at 4 36 53 pm](https://user-images.githubusercontent.com/14250339/29293004-f74f1eae-810e-11e7-8d65-5d240e9ac2f4.JPG)

**Comment by josephtocci** [comment]
The second case has already been fixed in the current branch, will be seen in the next release.

I'll fix the second case next time I'm in the autocomplete.

**Comment by crosstocci** [comment]
Fixed in next release.
