### ISSUE TITLE
Postage Electron Graphical Explain Is not working

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/postage#38]
d3.js causes an error.

After this error SELECT results cannot be scrolled through.

Could it be that d3 is trying to use window.exports instead of defining itself in the global namespace?

**Comment by michaeltocci** [comment]
I think we need to add a check to make sure dot.js, d3.js and fastclick are all defined in the global namespace. This way, we wont release if there is a regression.

**Comment by josephtocci** [comment]
Issue is unreplicatable on latest version.
