### ISSUE TITLE
E'\n's are converted to actual newlines.

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#380]
PGAdmin does this too, I'm not sure it can be fixed. But it is really annoying so if there is a way to do it I'd like to know.
![screen shot 2017-08-18 at 11 16 47 am](https://user-images.githubusercontent.com/14278246/29487598-ae3fe1ba-84c1-11e7-9265-bdf4cad23944.png)

**Comment by justintocci** [comment]
I don't see why we can't do a find for single quote, new line, single quote sequences and just replace them with " E'\n' ". Can't you just add this to beautify button?

**Comment by justintocci** [comment]
Actually, I've thought about it and it is possible that that would cause an issue, but if you search for " '
'::text "
and replace that with E'\n'::text then you will be ok to five nines for sure.

**Comment by nunziotocci** [comment]
I'd like to point out that this will match if it shows up inside dollar tags.
But, in the rare event that can happen, I'd say that there's probably something else wrong.

**Comment by justintocci** [comment]
If this did occur in a dollar tag context, it's very likely the sequence is there because it is a SQL string. In that case, the E'\n'::text will still work if the database is PostgreSQL. I don't think we need to worry about it. If someone posts an issue we can address it then.
