### ISSUE TITLE
Record Highlight is not obvious enough

### ISSUE THREAD

**Issue by jentocci** [workflowproducts/postage#39]
When I am in a field, record indicator is not obvious enough:

![screen shot 2016-11-05 at 3 24 53 pm](https://cloud.githubusercontent.com/assets/23283948/20033385/4abdf2c0-a36d-11e6-99cc-27aaaabe04fa.png)

**Comment by josephtocci** [comment]
Do you want the whole record blue or do you want a more obvious color for the record number?

**Comment by jentocci** [comment]
I think both. Make the whole row a brighter blue.
 
Regards,
Jen Tocci, President
Workflow Products LLC
Call, Text, FaceTime:
(817)899-7232

**Comment by josephtocci** [comment]
Will be seen in the next release.
