### ISSUE TITLE
Copy/Paste in "Edit Table" causes Selection to be displaced.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#395]
When copying out of "Edit Table" a few cells, Paste into "Edit Table" causes selection to shift up one record.

The actual copy and paste works fine, but it's disconcerting and it makes you think you did the wrong thing because the selection should be on the pasted cells but it's shifted up one record.

**Comment by nunziotocci** [comment]
Fixed in cddd80fe0b58a2efed812c27545998ed10048221
