### ISSUE TITLE
Refresh of browser causes blank line to be selected.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#4]
![screen shot 2016-09-20 at 7 05 56 pm](https://cloud.githubusercontent.com/assets/14250339/18693234/cf5ad34e-7f65-11e6-9f9b-317544897c1a.JPG)

When refreshing the browser window, the object tree on the left should either re-open to the selected item so that the correct item is selected or the selection should be cleared.

**Comment by michaeltocci** [comment]
This will be fixed in the next release.
