### ISSUE TITLE
Column headings disappear after scrolling

### ISSUE THREAD

**Issue by jentocci** [workflowproducts/postage#40]
I lose the column headings when I scroll down:

Before scrolling:
![screen shot 2016-11-05 at 3 30 01 pm](https://cloud.githubusercontent.com/assets/23283948/20033395/7909dfcc-a36d-11e6-9e1f-d6e4c0f8c42e.png)

After scrolling:
![screen shot 2016-11-05 at 3 30 15 pm](https://cloud.githubusercontent.com/assets/23283948/20033398/7ed903d8-a36d-11e6-9ca7-242c22a54547.png)

**Comment by crosstocci** [comment]
Fixed in next release.
