### ISSUE TITLE
Removing the "Postage is no longer being maintained" / Customizing the announcements page

### ISSUE THREAD

**Issue by Vonatzki** [workflowproducts/postage#400]
Hi Workflow,

Hope you can still help me on how to modify the splash page upon login of a user to the Postage client server (see picture below).

Some of the less "tech-savvy" users in my company might be alarmed if they see the big red text and think about it as a database-related maintenance and maybe stop using it altogether until it goes away.

Furthermore, I'm planning to put some custom announcements in there in order to guide users on how to query our database.

Thanks Workflow!

P.S. It was a good run. Thank you for making my life easier as the de-facto DBA in my team.

![capture](https://user-images.githubusercontent.com/12231265/29802112-f56608da-8ca5-11e7-9cb8-de063d81b7d9.PNG)

**Comment by nunziotocci** [comment]
@Vonatzki,

I just closed #398 which will allow you to change the splash page.

I see you're on windows (I recognize the scrollbar), so you'll need VS2017 to compile postage.
After you Clone/Download postage, the splash page will be in `<repo>/src/web_root/postage/splash.html`.
To package:
1. Start Menu > Visual Studio 2017 > x86 Native Tools Command Prompt (this has the required tools in %PATH%)
2. cd into the cloned postage
3. `package-windows.bat`

If you would like to point the splash page to an internal webserver, you need to change two files.
- `src/web_root/postage/app/resources/pg-9.2-other.js`
- `src/web_root/postage/app/resources/ws-home.js`
In both files, search for `/postage/splash.html` and replace with your URL.

For information on packaging on other OSes, see PACKAGE.txt

**Comment by Vonatzki** [comment]
Closing this issue
