### ISSUE TITLE
Auto-complete can't be used

### ISSUE THREAD

**Issue by hachanuy** [workflowproducts/postage#41]
I just tried the software, I love the UI. But there is a problems when the editor suggest a completion when i'm writing a query, it can't be done by hitting Enter, I have to click the completion by mouse which makes it kind of annoying, can you please check and have it fixed? I'm using a Mac, by the way, it could be just a problem on that OS.

**Comment by michaeltocci** [comment]
Welcome! To choose a completion using the keyboard you can use the Tab key.

Let me know if that works for you. If you prefer the return key, perhaps we could add a preference that allows you to define which key causes a completion to be chosen.

**Comment by hachanuy** [comment]
yes, that would be better since most IDEs support return key for auto-complete so it would be more familiar for more people.

**Comment by michaeltocci** [comment]
Well, since using the `Return` key is more common, perhaps we should just switch to the `Return` Key. I see now that adding a preferences dialog would make it kind of hidden.

The reason we originally decided to use the `Tab` key was because we wanted our autocomplete to be unobtrusive. Using the return key would mean having the user dismiss the autocomplete so that they could add a new line. However, I now think it's possible to use the `Return` key in a way that would be unobtrusive.

**Here's my proposal for the minimum changes to switch to the return key for completion:**

- When the autocomplete first pops up, no item is selected.
- Arrow down must be pressed to select the first item in the autocomplete list.
- If an item is selected in the list: return chooses that item.
- If no items are selected in the list: return dismisses the choice list.

_Other than these changes, autocomplete would remain the same._

The crucial thing to notice is that the `Return` key is only used **if** you arrow into the autocomplete. This way you don't need to dismiss the autocomplete before adding a new line.

**Comment by justintocci** [comment]
I'm ok with making the autocomplete keys configurable. 

Note that we should post a map here of what keys do what and plan it out thoroughly before we go messing around. A lot of thought went into our autocomplete key choices and I don't want to make a mess.

We need to also remember that a stated goal of the Postage project is parity with Microsoft SQL Server Management Studio. For the following examples I'm going to refer to the autocomplete key configuration in that program.

MSSMS has TAB, SPACE and RETURN all trigger the autocomplete to complete a word. This can give a first time user a feeling of being trapped in the autocomplete. ESC will disable the autocomplete, but that causes the fingers to leave the home keys and seems strange that you would have to do that.

MSSMS does the same thing for four keys. We felt that was overkill so we did:
    TAB triggers autocompletion
    ESC dismisses autocomplete
    RETURN dismisses autocomplete and adds a line break 
    SPACE dismisses and adds a space

Consider the following autocomplete:

full_
    fullBoat
    fullTime

If we were to switch RETURN to trigger autocompletion then a user who wanted "full" and then a line break would have to type "full", then ESC to dismiss autocomplete, then RETURN to add a line break. In the current system they just type "full" then RETURN. 

I'm not willing to do that so it will need to be a stored user preference. 

@hachanuy,

**Comment by josephtocci** [comment]
I don't like any key to finish the autocomplete, what if I want to type "abs" then move to the next line using arrow down, or add a newline, or a tab character? Less is more in this case. The escape key dismisses the autocomplete, but breaks the workflow. I dismiss the autocomplete more often than I use it but everybody always make it more work to dismiss than to use. We should go in the other direction. My suggestion:

State 1:
Autocomplete shows up
Only shows one option, and is transparent.
Arrow keys, return key, tab key do nothing, they just make changes to the editor as expected.

User presses and releases option key while autocomplete is shown, moves to state 2.
If another key is pressed while option key is held down, no change.

State 2:
Autocomplete modal changes from transparent to opaque and increases size.
Arrow keys change autocomplete selection.
Return key and tab key chooses the selected option in the autocomplete, this dismisses the autocomplete and changes the text in the editor.
Escape key will not dismiss the autocomplete, but it will unselect it and go to state 1.
User presses and releases option key while autocomplete is shown, moves to state 1.
If another key is pressed while option key is held down, no change.

This way, it is unobtrusive, and still reasonable quick:
Option, Return
Option, Arrow-down, Return

Alternatively, holding down the option key moves the autocomplete to state 2, releasing it moves back to step 1. Then it's a little quicker:
Option-Arrow-down-Return

The Command key might be a little easier to reach on most keyboard, alternatively the windows key on windows keyboards.

**Comment by justintocci** [comment]
In reaction to Michael's post above I say that would be a step backward because currently, to use the first autocomplete suggestion you just type TAB. Under your proposal, autocomplete becomes an additional key every time.

**Comment by justintocci** [comment]
In reaction to Joseph's post above I say it again, 
that would be a step backward because currently, to use the first autocomplete suggestion you just type TAB. Under your proposal, autocomplete becomes an additional key (option) every time.

**Comment by josephtocci** [comment]
We're not handling the original problem, the original problem is that OP didn't know that tab is how you autocomplete. Lets just put a label on the autocomplete saying to his tab to autocomplete. Then there will be no confusion.

**Comment by justintocci** [comment]
Yea! I like it. If someone really wants it to be configurable then please post a mock up of what you might like to see. We can still do that at some point.

**Comment by justintocci** [comment]
Re-opening because we want a label on the autocomplete dropdown saying "Press [TAB] to complete word" or something similar. 

Also, if anyone is interested in configuring the autocomplete, get us a list of items/keys or whatever and we'll consider that also.

**Comment by justintocci** [comment]
I've removed the first-time-contrib tag. Lets get this done.

**Comment by josephtocci** [comment]
Done. Will be seen in the next release.

![screen shot 2016-11-24 at 10 05 49 am](https://cloud.githubusercontent.com/assets/14278246/20604752/a35a7092-b22d-11e6-9b62-9f38e1ca8991.png)
