### ISSUE TITLE
SQL Beautifier

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/postage#42]
PGAdmin has a built in Beautifier for SQL, and I think it would benefit us to have one as well.

**Comment by nunziotocci** [comment]
It turns out that PGAdmin doesn't have a beautifier  per say, but I still think we should have one.

**Comment by josephtocci** [comment]
Here are some I found on github. Google searching didn't really help. Github searching did as I was able to limit to javascript projects.

https://github.com/SethRAH/format-sql
https://github.com/mysqljs/sqlstring
https://github.com/camilojd/sequeljs
https://github.com/zeroturnaround/sql-formatter

All are MIT and some are larger than others. We should test all of them and figure out which one we want.

**Comment by nunziotocci** [comment]
There's also this: https://github.com/google/code-prettify

**Comment by nunziotocci** [comment]
Scratch that last one, that is just a syntax highlighter for blogs and such.

**Comment by josephtocci** [comment]
I used
https://github.com/SethRAH/format-sql
as a basis for another node formatter, now I need to convert it for use in a browser.

**Comment by josephtocci** [comment]
var formatSql = require('./beatifier.js');
var strFormattedSQL = formatSql.formatQuery(strUnformattedSQL);

Use this code

**Comment by josephtocci** [comment]
Wrong issue closed

**Comment by justintocci** [comment]
Add a button to the SQL tab to trigger this.

**Comment by josephtocci** [comment]
Button added, will be seen in the next release.
