### ISSUE TITLE
Fix compilation in MSYS2 (With BigSQL)

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/postage#44]

**Comment by nunziotocci** [comment]
I would like to point out that I am testing with MSYS2 and BigSQL's PostgreSQL distribution instead of normal MinGW and PostgreSQL

**Comment by nunziotocci** [comment]
So it turns out that there is a bug in MSYS2's realpath, so this will be put on hold.

Alexpux/MSYS2-packages#763

**Comment by josephtocci** [comment]
I took realpath.c from freebsd:
[realpath.txt](https://github.com/workflowproducts/postage/files/628382/realpath.txt)

Seems like it will work, maybe rename the function and bring it in to our code conditionally for mingw?

**Comment by josephtocci** [comment]
Took this one from OpenBSD:
[realpath.txt](https://github.com/workflowproducts/postage/files/628396/realpath.txt)

Seems like it's the same, and from the same author.

**Comment by nunziotocci** [comment]
Closing,  see #103 for details.
