### ISSUE TITLE
Postage Log-In Failure to Connect

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/postage#50]
When you try to log into a Postgres instance that's on another network but your not VPN'd to that network, there is a long wait where Postage is trying to contact the database. At some point the log-in request times out.

While you're waiting you can't do anything. If you try to VPN while Postage is still trying to connect, Postage still doesn't connect. At this point you can either quit Postage or wait for the log-in to time out.

What I propose to fix this is you need to be able to cancel a log-in request. This way you can connect to the VPN and then try to connect again without waiting on Postage to time out and without quitting Postage.

**Comment by josephtocci** [comment]
Will be seen in next release.
