### ISSUE TITLE
Postage Needs Snippets In Ace Viewer (tabs)

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/postage#52]
When you look at an object's script in Postage, it should save a copy of it in the browser so that you can easily go back to a previous version.

Since it would only be saved in the browser, the history would be lost if you refreshed. However, I still believe this feature would be valuable.

The problem I'm trying to solve is I that copied the code of a FUNCTION so that I could write a new FUNCTION without having to write my usual FUNCTION code, and I forgot to rename the new FUNCTION before running the script. So, I overwrote my old FUNCTION. Luckily, I was to undo back to the way my old FUNCTION was and re-create it. I realize now that I could've just gone into the backups and retrieved the code. However, it would've been convenient to be able to retrieve the FUNCTION's code using the feature I described above.

**Comment by justintocci** [comment]
Actually, this worked pretty good, I don't see an urgent need to improve it.

If I understand correctly, you started with an existing function, re-wrote it but forgot to re-name it, ran it, realized your mistake, clicked undo to get back to the original, then put the original back. This is perfect.

In future, if you need a new function you should start with a snippet, then copy the body of an existing function that may have code you want to refactor. 

I think a set of CREATE snippets is what we need, not yet another way to save code that will rapidly become obsolete.

**Comment by josephtocci** [comment]
Snippets for consideration:

snippet CREATE TABLE 
    CREATE TABLE ${1:schema}.${2:table} (
        id integer NOT NULL DEFAULT nextval(('${1:schema}.${3:global_seq}'::text)::regclass),
        ${4}
        create_login name DEFAULT "session_user"(),
        change_login name DEFAULT "session_user"(),
        create_stamp timestamp with time zone DEFAULT date_trunc('second'::text, ('now'::text)::timestamp with time zone),
        change_stamp timestamp with time zone DEFAULT date_trunc('second'::text, ('now'::text)::timestamp with time zone),
        CONSTRAINT ${2:table}_pk PRIMARY KEY (id)
    ) WITH (
        OIDS=FALSE
    );
    
    ALTER TABLE ${1:schema}.${2:view} OWNER TO postgres;

snippet CREATE VIEW
    CREATE OR REPLACE VIEW ${1:schema}.${2:view} AS
    ${4}
    
    ALTER TABLE ${1:schema}.${2:view} OWNER TO postgres;
    GRANT SELECT,UPDATE,INSERT,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE ${1:schema}.${2:view} TO ${3:trusted_g};

snippet CREATE FUNCTION
    CREATE OR REPLACE FUNCTION ${1:schema}.${2:function}(str_args text)
    RETURNS text AS
    $BODY$
    DECLARE
        ${4}
    BEGIN
        ${5}
    END;
    $BODY$
    LANGUAGE plpgsql VOLATILE
    COST 100;
    
    ALTER FUNCTION ${1:schema}.${2:function}(str_args text) OWNER TO postgres;
    GRANT EXECUTE ON FUNCTION ${1:schema}.${2:function}(str_args text) TO ${3:trusted_g};

snippet CREATE GROUP
    CREATE ROLE ${1:trusted_g}
        NOLOGIN
        NOCREATEROLE
        NOSUPERUSER
        INHERIT
        NOCREATEDB
        NOREPLICATION
        CONNECTION LIMIT -1
        VALID UNTIL 'infinity';

snippet CREATE ROLE
    CREATE ROLE ${1:user_name}
        LOGIN PASSWORD '${2:password}'
        NOCREATEROLE
        NOSUPERUSER
        INHERIT
        NOCREATEDB
        NOREPLICATION
        CONNECTION LIMIT -1
        VALID UNTIL 'infinity';
    
    GRANT ${3:trusted_g} TO ${1:user_name};

snippet CREATE SEQUENCE
    CREATE SEQUENCE ${1:schema}.${2:sequence}
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        CACHE 1
        NO CYCLE;
    
    ALTER SEQUENCE ${1:schema}.${2:sequence} OWNER TO postgres;
    
    GRANT ALL ON TABLE ${1:schema}.${2:sequence} TO postgres;

snippet RESTART SEQUENCE
    ALTER SEQUENCE ${1:schema}.${2:sequence} RESTART;

**Comment by josephtocci** [comment]
Updated snippets for consideration:
[snippets.txt](https://github.com/workflowproducts/postage/files/768936/snippets.txt)

**Comment by josephtocci** [comment]
Forgot select into:
[snippets.txt](https://github.com/workflowproducts/postage/files/768978/snippets.txt)

**Comment by crosstocci** [comment]
Added SQL snippets in next release.
