### ISSUE TITLE
PostgreSQL Version

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#53]
When you aren't on the latest version of Postage, the version number appears as red text on the homepage. We should do the same thing for PostgreSQL.

**Comment by justintocci** [comment]
I agree. Seems like a good thing for a new contributor. Lets give it a few weeks before we do this.

**Comment by nunziotocci** [comment]
I made it so that when you log in, the splash screen now shows:
"Connected to PostgreSQL version v9.2.4"
With the version number in red for versions prior to v9.2.0

Do we want to do something about being more than a few patches behind?

**Comment by josephtocci** [comment]
> Do we want to do something about being more than a few patches behind?

I just did. But we need to remember every time that postgres updates, we need to update the splash page. A good time to check is when postage updates.
