### ISSUE TITLE
Mac dmg background image too big

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#61]
The dmg finder window has the text cut off at the bottom. I have to resize it to read it.

![screen shot 2016-11-28 at 3 29 26 pm](https://cloud.githubusercontent.com/assets/14278246/20688454/6f8729a2-b586-11e6-8def-64b2cad08da2.png)

**Comment by nunziotocci** [comment]
Technically, the windowis the exact right height for the image, but there is an extra toolbar that isn't accounted for. I will just add some height to the image below the text so that if the toolbar is there, it doesn't interfere with readability.
