### ISSUE TITLE
Version Number in Splash Screen Does Not Match Current

### ISSUE THREAD

**Issue by anthonydb** [workflowproducts/postage#62]
Minor thing, but whenever I download new versions of Postage, the splash screen keeps showing an old version number; in this case, I installed v3.1 and the splash shows v2.2:

<img width="745" alt="screen shot 2016-11-28 at 8 36 38 pm" src="https://cloud.githubusercontent.com/assets/273891/20693214/de87bf0a-b5aa-11e6-8f9f-ae60018e2ed7.png">

Also, spelling of "development" needs correcting. Sorry, I'm a nitpicker on spelling.

**Comment by josephtocci** [comment]
Hmm, that version number has to do with the binary version, not the electron version. But those versions should be the same. It would make things simpler.
