### ISSUE TITLE
When running SQL, Errors are cut off. 

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#65]
# in Postage it looks like
ERROR:  invalid input syntax for integer: "BD500LVDT-Q"
CONTEXT:  SQL statement " UPDATE pilot.temp_demand SET total_required = coalesce(("_2016_11_28_DK23400")::integer,0) + coalesce(("_2016_12_09_BD500LVDT-Q")::integer,0) + coalesce

# in PGAdmin it looks like:
ERROR:  invalid input syntax for integer: "BD500LVDT-Q"
CONTEXT:  SQL statement " UPDATE pilot.temp_demand SET total_required = coalesce(("_2016_11_28_DK23400")::integer,0) + coalesce(("_2016_12_09_BD500LVDT-Q")::integer,0) + coalesce(("_2016_12_15_453400Q5")::integer,0) + coalesce(("_2016_12_15_453400Q6")::integer,0) + coalesce(("_2017_01_02_456000Q5")::integer,0) + coalesce(("_2017_01_03_453400Q4")::integer,0) + coalesce(("_2017_01_03_453400Q5")::integer,0) + coalesce(("_2017_01_03_456000Q4")::integer,0) + coalesce(("_2017_01_03_456000Q5")::integer,0) + coalesce(("_2017_01_03_456000Q6")::integer,0) + coalesce(("_2017_01_05_DK23400")::integer,0) + coalesce(("_2017_01_06_456000Q4")::integer,0) + coalesce(("_2017_02_01_DK23304")::integer,0) + coalesce(("_2017_02_01_453400Q4")::integer,0) + coalesce(("_2017_02_06_DK23400")::integer,0) + coalesce(("_2017_02_27_DK23401")::integer,0) + coalesce(("_2017_03_01_456000Q5")::integer,0) + coalesce(("_2017_03_10_456000Q4")::integer,0) + coalesce(("_2017_03_14_DK23401")::integer,0) + coalesce(("_2017_03_15_453400Q5")::integer,0) + coalesce(("_2017_03_15_453400Q6")::integer,0) + coalesce(("_2017_03_24_DK23402")::integer,0) + coalesce(("_2017_04_01_456000Q6")::integer,0) + coalesce(("_2017_04_10_DK23400")::integer,0) + coalesce(("_2017_05_30_DK23301")::integer,0) + coalesce(("_2017_06_07_DK23402")::integer,0) + coalesce(("_2017_06_08_DK23402")::integer,0) + coalesce(("_2017_06_15_DK23402")::integer,0) + coalesce(("_2017_07_28_DK23242")::integer,0) + coalesce(("_2017_10_02_DK23400")::integer,0)"
PL/pgSQL function kit_demand_qry() line 143 at EXECUTE statement

********** Error **********

ERROR: invalid input syntax for integer: "BD500LVDT-Q"
SQL state: 22P02
Context: SQL statement " UPDATE pilot.temp_demand SET total_required = coalesce(("_2016_11_28_DK23400")::integer,0) + coalesce(("_2016_12_09_BD500LVDT-Q")::integer,0) + coalesce(("_2016_12_15_453400Q5")::integer,0) + coalesce(("_2016_12_15_453400Q6")::integer,0) + coalesce(("_2017_01_02_456000Q5")::integer,0) + coalesce(("_2017_01_03_453400Q4")::integer,0) + coalesce(("_2017_01_03_453400Q5")::integer,0) + coalesce(("_2017_01_03_456000Q4")::integer,0) + coalesce(("_2017_01_03_456000Q5")::integer,0) + coalesce(("_2017_01_03_456000Q6")::integer,0) + coalesce(("_2017_01_05_DK23400")::integer,0) + coalesce(("_2017_01_06_456000Q4")::integer,0) + coalesce(("_2017_02_01_DK23304")::integer,0) + coalesce(("_2017_02_01_453400Q4")::integer,0) + coalesce(("_2017_02_06_DK23400")::integer,0) + coalesce(("_2017_02_27_DK23401")::integer,0) + coalesce(("_2017_03_01_456000Q5")::integer,0) + coalesce(("_2017_03_10_456000Q4")::integer,0) + coalesce(("_2017_03_14_DK23401")::integer,0) + coalesce(("_2017_03_15_453400Q5")::integer,0) + coalesce(("_2017_03_15_453400Q6")::integer,0) + coalesce(("_2017_03_24_DK23402")::integer,0) + coalesce(("_2017_04_01_456000Q6")::integer,0) + coalesce(("_2017_04_10_DK23400")::integer,0) + coalesce(("_2017_05_30_DK23301")::integer,0) + coalesce(("_2017_06_07_DK23402")::integer,0) + coalesce(("_2017_06_08_DK23402")::integer,0) + coalesce(("_2017_06_15_DK23402")::integer,0) + coalesce(("_2017_07_28_DK23242")::integer,0) + coalesce(("_2017_10_02_DK23400")::integer,0)"
PL/pgSQL function kit_demand_qry() line 143 at EXECUTE statement

**Comment by nunziotocci** [comment]
How does this look?
```
SEVERITY: ERROR
ERROR: invalid input syntax for integer: "test"
SQLSTATE: 22P02
DETAIL: 
HINT: 
QUERY: 
CONTEXT: SQL statement "SELECT coalesce(("_2016_11_28_DK23400")::integer,0) + coalesce(("_2016_12_09_BD500LVDT-Q")::integer,0) + coalesce(("_2016_12_15_453400Q5")::integer,0) + coalesce(("_2016_12_15_453400Q6")::integer,0) + coalesce(("_2017_01_02_456000Q5")::integer,0) + coalesce(("_2017_01_03_453400Q4")::integer,0) + coalesce(("_2017_01_03_453400Q5")::integer,0) + coalesce(("_2017_01_03_456000Q4")::integer,0) + coalesce(("_2017_01_03_456000Q5")::integer,0) + coalesce(("_2017_01_03_456000Q6")::integer,0) + coalesce(("_2017_01_05_DK23400")::integer,0) + coalesce(("_2017_01_06_456000Q4")::integer,0) + coalesce(("_2017_02_01_DK23304")::integer,0) + coalesce(("_2017_02_01_453400Q4")::integer,0) + coalesce(("_2017_02_06_DK23400")::integer,0) + coalesce(("_2017_02_27_DK23401")::integer,0) + coalesce(("_2017_03_01_456000Q5")::integer,0) + coalesce(("_2017_03_10_456000Q4")::integer,0) + coalesce(("_2017_03_14_DK23401")::integer,0) + coalesce(("_2017_03_15_453400Q5")::integer,0) + coalesce(("_2017_03_15_453400Q6")::integer,0) + coalesce(("_2017_03_24_DK23402")::integer,0) + coalesce(("_2017_04_01_456000Q6")::integer,0) + coalesce(("_2017_04_10_DK23400")::integer,0) + coalesce(("_2017_05_30_DK23301")::integer,0) + coalesce(("_2017_06_07_DK23402")::integer,0) + coalesce(("_2017_06_08_DK23402")::integer,0) + coalesce(("_2017_06_15_DK23402")::integer,0) + coalesce(("_2017_07_28_DK23242")::integer,0) + coalesce(("_2017_10_02_DK23400")::integer,0)
        FROM (
            SELECT
                'test'::text AS "_2016_11_28_DK23400",
                'test'::text AS "_2016_12_09_BD500LVDT-Q",
                'test'::text AS "_2016_12_15_453400Q5",
                'test'::text AS "_2016_12_15_453400Q6",
                'test'::text AS "_2017_01_02_456000Q5",
                'test'::text AS "_2017_01_03_453400Q4",
                'test'::text AS "_2017_01_03_453400Q5",
                'test'::text AS "_2017_01_03_456000Q4",
                'test'::text AS "_2017_01_03_456000Q5",
                'test'::text AS "_2017_01_03_456000Q6",
                'test'::text AS "_2017_01_05_DK23400",
                'test'::text AS "_2017_01_06_456000Q4",
                'test'::text AS "_2017_02_01_DK23304",
                'test'::text AS "_2017_02_01_453400Q4",
                'test'::text AS "_2017_02_06_DK23400",
                'test'::text AS "_2017_02_27_DK23401",
                'test'::text AS "_2017_03_01_456000Q5",
                'test'::text AS "_2017_03_10_456000Q4",
                'test'::text AS "_2017_03_14_DK23401",
                'test'::text AS "_2017_03_15_453400Q5",
                'test'::text AS "_2017_03_15_453400Q6",
                'test'::text AS "_2017_03_24_DK23402",
                'test'::text AS "_2017_04_01_456000Q6",
                'test'::text AS "_2017_04_10_DK23400",
                'test'::text AS "_2017_05_30_DK23301",
                'test'::text AS "_2017_06_07_DK23402",
                'test'::text AS "_2017_06_08_DK23402",
                'test'::text AS "_2017_06_15_DK23402",
                'test'::text AS "_2017_07_28_DK23242",
                'test'::text AS "_2017_10_02_DK23400"
        ) em"
PL/pgSQL function testtesttestdeletemetest() line 5 at SQL statement
POSITION: 
```

**Comment by justintocci** [comment]
Dude, why is the POSITION cut off?

**Comment by nunziotocci** [comment]
The position field is empty for that error.

**Comment by justintocci** [comment]
Ok, let's just get this in production this week ok? This is a fairly big problem to have this late in the game.

**Comment by josephtocci** [comment]
This fix is in the latest postage.
