### ISSUE TITLE
"Clip Options" states that changes are effective immediately after clicking "save", but they aren't. 

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#66]
steps to reproduce on windows:

select a result window cell value. 
click ctrl-c
click ctrl-v to paste into a tab - i get the column name and the data but i just want the data
click "clip options" 
select "only when selected" 
click save
paste into a tab - i get the column name and the data but i just want the data AGAIN
select a result window cell value. 
click ctrl-c
click ctrl-v to paste into a tab - i get the just the data

do not remove the label 'changes are effective immediately after clicking "save"'. please just fix it to work as intended.

**Comment by nunziotocci** [comment]
It looks like you can use document.execCommand('copy') when the popup closes on these browsers:
![capture1](https://cloud.githubusercontent.com/assets/7560749/20895571/960a751c-badf-11e6-91b0-665ae88075e9.PNG)
![capture2](https://cloud.githubusercontent.com/assets/7560749/20895572/960e8a8a-badf-11e6-8f6c-d1277c3eba36.PNG)

**Comment by justintocci** [comment]
Right, right. Forgot this was a clipboard security issue. We can't do this. What was I thinking? Just make the note say the right thing.

**Comment by nunziotocci** [comment]
Fixed in https://github.com/workflowproducts/postage/commit/749794ffcb0ee1b5c5df893c3a5c6f925fb8e84f

**Comment by nunziotocci** [comment]
I made it say 'You need to re-copy your data after clicking "Save"'.
