### ISSUE TITLE
Windows version 3.1.0 only gives white screen

### ISSUE THREAD

**Issue by renzok** [workflowproducts/postage#67]
Hi,

I just downloaded the Windows 3.1.0 zip version and executed the binary on a windows 7 professional service pack 1.

 I just get a white screen. No error, no nothing . Do I miss something?

![postage-3 1 0-white-screen](https://cloud.githubusercontent.com/assets/3148886/20902988/f2eae672-bb39-11e6-891e-2b541b61ff09.png)

thx,
renzo

**Comment by nunziotocci** [comment]
Can you Go "View > Toggle Developer Tools" in the menu and send a screenshot?

**Comment by justintocci** [comment]
I'm stuck, can't reproduce. 
renzok, please go to "View > Toggle Developer Tools" and look under "console". We need to see if there are any errors there.

**Comment by renzok** [comment]
thx for fast reply.

I get an empty page:

![postage-3 1 0-white-screen](https://cloud.githubusercontent.com/assets/3148886/20903548/fdb27e2e-bb3b-11e6-86c1-fc214434d630.png)

and no errors in console:

![screenclip](https://cloud.githubusercontent.com/assets/3148886/20903597/32b5e106-bb3c-11e6-9e46-6df1302d8164.png)

**Comment by nunziotocci** [comment]
Can I see the network pane of the devtools?

**Comment by renzok** [comment]
![screenclip](https://cloud.githubusercontent.com/assets/3148886/20903687/9c2f1404-bb3c-11e6-9aea-4efd576bd698.png)

**Comment by renzok** [comment]
In devtools "security" I get a message that the page is not secure. Which engine is it? WebKit?

**Comment by nunziotocci** [comment]
Can you run this command in CMD.exe:
```
AppData\Local\Programs\Postage\3.1.0\Postage.exe
```
And send me the output?

**Comment by nunziotocci** [comment]
> In devtools "security" I get a message that the page is not secure. Which engine is it? WebKit?

It is Blink, which is what Google Chrome uses.

**Comment by renzok** [comment]
> Can you run this command in CMD.exe:
>AppData\Local\Programs\Postage\3.1.0\Postage.exe
> And send me the output?

8872 closed with code 3221225781

**Comment by nunziotocci** [comment]
Are you on 64-bit or 32-bit?

**Comment by renzok** [comment]
64

**Comment by nunziotocci** [comment]
Can you show me what is in the "AppData\Local\Programs\Postage\3.1.0\resources\app\postage" folder?

**Comment by renzok** [comment]
![screenclip](https://cloud.githubusercontent.com/assets/3148886/20904031/10e0dfa2-bb3e-11e6-8b41-cd331eb2e4f3.png)

**Comment by nunziotocci** [comment]
Try double clicking on `postage.exe` in that folder.

**Comment by nunziotocci** [comment]
The 3221225781 error code in my experience means that a library file has the wrong arch, or is missing. If you double click an app it will usually tell you which one.

**Comment by renzok** [comment]
![screenclip](https://cloud.githubusercontent.com/assets/3148886/20904093/5581d418-bb3e-11e6-8523-f813db6ea9e3.png)

I think, we are getting closer...

**Comment by nunziotocci** [comment]
Do you have any pending updates?

**Comment by nunziotocci** [comment]
That dll is part ot the Microsoft Universal CRT, which is not installed by default on Windows 7.

**Comment by renzok** [comment]
71 optional updates, no clue which one it could be. (laptop from work, per-configured by IT)

**Comment by justintocci** [comment]
Ok, here is a link. 

http://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe

If this fixes it, then great. Nunzio is going to make sure this DLL is included in future releases of Postage...

**Comment by renzok** [comment]
> http://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe

great, that works now and looks nice so far :)

**Comment by justintocci** [comment]
Ok, I think I know how this was missed. Our development testing windows 7 box has the optional updates installed.

The Universal CRT appears to be optional update KB2999226 (https://support.microsoft.com/en-us/kb/2999226)

Let's leave this open until we decide what to do.

Renzok, feel free to email justin@wfprod.com your address and I'll send you a thank you for the issue. I think you're only the third person to post an issue and we really appreciate it.

**Comment by nunziotocci** [comment]
I made the Windows installer check for `ucrtbase.dll` in the three possible places it is installed in.

If it is not preset it opens a dialog with this message:
```
To install Postage, you need to install the Universal CRT.<br />
Press OK to open the download page.
```

**Comment by nunziotocci** [comment]
The reason I made it so that users have to install it is because even though I could have bundled it, it is better to have the user install it anyway.
