### ISSUE TITLE
Paste into datasheet with text data missing cell

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/postage#68]
Pasting to the Postage datasheet only works if every record has the same number of cells. If you try to paste using this data:
```
test1	asdf1	qwer8
test2	asdf2	qwer7
test3	asdf3	qwer6
test4	asdf4	qwer5
test5	asdf5	qwer4
test6	asdf6	qwer3
test7	asdf7
test8	asdf8	qwer1
```

You get this error:
![failure](https://cloud.githubusercontent.com/assets/10438221/20930391/d3a9e57a-bb92-11e6-86b9-d78f668889f5.png)

To fix this, add an `if` statement to the function in the error (frames/datagrid.js) to check to make sure that it's trying to get data from a cell that exists, if the cell doesn't exist, add NULL for the value of that cell.

**Comment by josephtocci** [comment]
Done, will be seen in the next release.
![screen shot 2016-12-06 at 10 24 28 am](https://cloud.githubusercontent.com/assets/14278246/20933610/3741101c-bb9e-11e6-8185-4b500f22f47f.png)
