### ISSUE TITLE
Table Dependencies

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#70]
Dependencies need to be added under the table in the tree view.
#9

**Comment by justintocci** [comment]
Actually there are a few other improvements that need to be covered. 

We lost the "TBL" or whatever initials were showing that tables are tables when we got the triangle. any way we could get that back?

We did add column lists for Tables, but we still need them for views. 

When we click a column name it refreshes the tab on the right. Nothing should happen when you click a column name. Note that "Postage tree only open folder when you click on the triangle #71" is related to this issue.

**Comment by michaeltocci** [comment]
The "TB" initials have been added back to the tables.
Clicking on a column no longer refreshes the tab.
Views are now able to show the column list within.

These changes will be seen in the next release.

I am not closing this issue yet because we still want to add these items to the table dependency list:
    triggers
    indexes (includes primary keys and constraints)

**Comment by crosstocci** [comment]
Inconsistency in triangles sizes on windows is now fixed

**Comment by crosstocci** [comment]
Tables and Views now have triangles.

**Comment by justintocci** [comment]
I am aware of Michael's idea that we add triggers and indexes under the triangle, but I don't think it's necessary right now. I'm going to close this. If someone in the community thinks it's a priority then please open a new issue for it.
