### ISSUE TITLE
Postage tree only open folder when you click on the triangle

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/postage#71]
In other DBMSs object trees you can click on the triangle to open (for example) a schema and it won't show you the schema's script, it'll just open it's contents.

This feature would be implemented as such:

Because we use an Ace editor for our tree view, in the selection event where we handle the click, we need to do something like this (pseudocode):

```
if (typesOfSelectedLine contains 'folder' && cursorColumnNumber <= (positionOfLineTriangle + 2)) {
    only run folder load
} else {
    run everything
}
```

`positionOfLineTriangle + 2` includes the triangle and the space after it.

Reference Image:
![schemas](https://cloud.githubusercontent.com/assets/10438221/20943534/6e71cc4e-bbc5-11e6-858a-0b9f99b8ccba.png)

**Comment by justintocci** [comment]
There are two behaviors here.

When you click a category, like "Functions", it should open the folder. 

When you click an object(but not it's triangle), like schema "aco", or a table name, it should refresh the script on the right, but it should not open the triangle. 

When you click an object's triangle, it should open the triangle/folder.

I experimented with changing the backgrounds/colors to make this obvious to the user but it all looked like hell so skip that.

**Comment by josephtocci** [comment]
I have done this, but when you click the script while it is already open, it closes and you have to click it again to see the script.

**Comment by michaeltocci** [comment]
Fixed, will be seen in the next release. When the folder was clicked it was only running your code when the folder was closed and it skipped that code if it was open.
