### ISSUE TITLE
"Download Schema" feature is broken for some large schemas.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#73]
Steps to reproduce:

Connect to company 'R', ask justin if you don't know who this is. Click on 'pilot' schema and click the download schema button. Uncheck everything but the views.

Notes:

Postage definitely freezes. I didn't track down where but suspect it's a websocket reply issue.

It works for small schemas. Try 'tra' schema. works fine.

The name "Download Schema" implies it will be downloaded but it really just puts it in a tab. I'd like to re-name it "Schema To Script" or something.

**Comment by crosstocci** [comment]
Download schema has been renamed to "Dump schema to script".

**Comment by josephtocci** [comment]
This works on both Mac and Windows, so this must've been fixed when Michael was working on the Dump schema button.
