### ISSUE TITLE
PEV has cool features we need.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#77]
http://tatiyants.com/pev/#/plans/plan_1481165209666

slowest!! "bad estimate", costliest, largest....

also, the popup when you click on a node is much better than ours.

Also, check out the "graph metric" options...

love it, we need it.

**Comment by nunziotocci** [comment]
The link you provided shows nothing for me, here is a screenshot of one of my views:
![image](https://cloud.githubusercontent.com/assets/7560749/21201365/4f94f8cc-c210-11e6-991d-fd1248e50a0c.png)
