### ISSUE TITLE
If this is easy to do, please move find popup off of scroll bar.

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/postage#78]
![screen shot 2016-12-08 at 5 24 22 pm](https://cloud.githubusercontent.com/assets/14250339/21031860/656dcbe6-bd6b-11e6-87fa-9e4a249f259a.JPG)

The scroll bar gets hidden by the find window. If this is easy to do, please move find popup off of scroll bar.

**Comment by josephtocci** [comment]
Done, will be seen in next release.
