### ISSUE TITLE
Allow rds_superuser

### ISSUE THREAD

**Issue by AdeelK93** [workflowproducts/postage#90]
Since AWS RDS doesn't allow for the creation of super users, would it be possible to allow [rds_superuser](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.html) role to use postage? The permission set should be nearly the same. Thanks!

**Comment by nunziotocci** [comment]
In the `postage.conf` file, by default, the `super_only` config variable is true. If you set this to false it will not error.

So you need to change this:
```
# super_only = true
```

To this:
```
super_only = false
```

**Comment by AdeelK93** [comment]
Thanks for the quick reply! This works perfectly
