### ISSUE TITLE
Datasheet View: Can't hide or re-order columns

### ISSUE THREAD

**Issue by crosstocci** [workflowproducts/postage#93]
I open the column dialog:
![screenshot_20161231_150936](https://cloud.githubusercontent.com/assets/24857334/21579251/27a58e2c-cf6b-11e6-963d-4decdc8a45f6.png)

I can't click the show button, and when I try to re-order them:
![screenshot_20161231_145842](https://cloud.githubusercontent.com/assets/24857334/21579250/10d5e732-cf6b-11e6-8284-182eb70770ee.png)

When I refresh the datasheet after trying to re-order them:
![screenshot_20161231_145750](https://cloud.githubusercontent.com/assets/24857334/21579255/49053d4c-cf6b-11e6-87e6-f70de373a7e6.png)

**Comment by michaeltocci** [comment]
Fixed.

The issue was caused because I added some code to GS.openDialogToElement that caused the `after open` callback to run more than once.

Will be seen in the next release.
