### ISSUE TITLE
Loading records is confusing

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/postage#96]
When you run a query, you get a "Stop Execution" button. When the execution is finished this button goes away. This is all correct behavior.

However, when loading lots of records, the query finishes executing but the records are still loading. So, you just sit there because you can't cancel the loading.

We need a progress bar for the record loading step. This progress bar would use the number of records and the number of responses to calculate the position. To the right of the progress bar, there should be a button (like an "X" icon) to cancel the loading.

**Comment by justintocci** [comment]
If the progress bar is preventing this from being implemented then I'd rather just get a "Stop Loading" button. Let's get this done and close it.

**Comment by michaeltocci** [comment]
Basically, we need a button to tell the websocket to cancel the responses. So, if there are too many responses, the user can tell the websocket to stop sending data back from that query.

**Comment by justintocci** [comment]
Nunzio, is the server side request for this in place? Can we add a button? Please get with Cross and let's make this happen this week.

**Comment by nunziotocci** [comment]
The server side of CANCEL is now working.

@crosstocci All you need to do is add a button that send a websocket CANCEL request.

**Comment by crosstocci** [comment]
Added in next release.
