### ISSUE TITLE
Configure script: `--without-ssl` option

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/postage#97]
This would disable SSL support in the Postage binary.

**Comment by justintocci** [comment]
This option would only be useful to people that want to compile Postage from source (without SSL), and then deploy behind a web server which would terminate the SSL connections.

Low priority.

**Comment by nunziotocci** [comment]
I can't do (simply) long options in a cross-platform manner, how does `-w` sound?

**Comment by justintocci** [comment]
ok

**Comment by nunziotocci** [comment]
I started this, then I figured out that we use LibreSSL AES for the cookie. Should I close this?

**Comment by justintocci** [comment]
Yes. Assuming OpenSSL or an equivalent API is available will only make it very hard for people to install when it is not present. I'd rather people have a slow install than a broken install. 

Close this and let's remember it if it ever comes up again.
