### ISSUE TITLE
Research Calloc speed increase

### ISSUE THREAD

**Issue by josephtocci** [workflowproducts/postage#98]
Supposedly using calloc instead of malloc increases speed in some situations, they are not equivalent as widely believed.

**Comment by josephtocci** [comment]
http://stackoverflow.com/questions/2688466/why-mallocmemset-is-slower-than-calloc

Theoretically it can be marginally faster, but the caveat is that a particular class of valgrind errors cannot be checked for. Explained in:
https://matt.sh/howto-c

We could make it so that in production we use calloc for the speed increase, for development we use malloc for the better valgrind errors. How should we proceed?

**Comment by justintocci** [comment]
up to you. Who are you waiting for? We haven't had any community feedback in weeks.

**Comment by josephtocci** [comment]
I wanted to hear from the other developers. I heard from Nunzio, he is not in favor of having a difference from production and development. I'm inclined to agree with him.

Unless we truly need a speed increase in the future I'm closing this. Re-open if we are looking to tune up performance.

**Comment by justintocci** [comment]
There should be no difference in code from production to development, but this is not what I thought we were discussing. I thought we were discussing putting in a way of making it use malloc only while using Valgrind. That would be quite different. 

I'm ok with closing this though.
