### ISSUE TITLE
Table - Column ID Case Sensitive?

### ISSUE THREAD

**Issue by kevinrsalisbury** [workflowproducts/postage#99]
Running postage 3.1.3 built from source on SLES 12 64 bit. 

Postage will throw an error when attempting to view a table where the ID of the column is not lower case. (Yes, I know this is not good practice and is easy to work around - however sometimes we inherit things we have little control over, and I thought you might want to address it a little better in Postage). An example error from Postage when you attempt to view a table where a column named "ColumnID" is not shown;

There was an error:

ERROR:  column "columnid" does not exist
LINE 4: ORDER BY ColumnID DESC
                 ^

ERROR POSITION: 2002

Click "OK" and you are placed back on the table edit page with a generic message "Can't load data".

**Comment by michaeltocci** [comment]
Fixed, will be seen in next release.

I added a `quote_ident` call when building the order by for the ID column.

Thanks for the feedback!
